import type { WorldAchievementDef } from '../../engine/core/types'

export const achievements: WorldAchievementDef[] = [
  {
    id: 'first_step',
    name: '踏入异世界',
    description: '完成第一局游戏',
    icon: '🌍',
    hidden: false,
    condition: 'event.count.birth_noble >= 1 | event.count.birth_common >= 1 | event.count.birth_slums >= 1',
    category: 'progress',
  },
  {
    id: 'dragon_slayer_ach',
    name: '屠龙者',
    description: '讨伐巨龙成功',
    icon: '🐉',
    hidden: false,
    condition: 'event.count.dragon_slay_attempt >= 1',
    category: 'combat',
  },
  {
    id: 'archmage_ach',
    name: '大贤者',
    description: '成为大魔导师',
    icon: '🧙',
    hidden: false,
    condition: 'event.count.master_spell >= 1',
    category: 'magic',
  },
  {
    id: 'hero_ach',
    name: '真正的勇者',
    description: '完成勇者之旅',
    icon: '🗡️',
    hidden: false,
    condition: 'event.count.hero_journey_start >= 1',
    category: 'epic',
  },
  {
    id: 'dark_lord_ach',
    name: '堕落之路',
    description: '走上暗黑之路',
    icon: '🌑',
    hidden: false,
    condition: 'event.count.dark_mage_tempt >= 1',
    category: 'dark',
  },
  {
    id: 'reincarnator_ach',
    name: '转生者的逆袭',
    description: '发明可乐',
    icon: '🥤',
    hidden: true,
    condition: 'event.count.reincarnated_invention >= 1',
    category: 'secret',
  },
  {
    id: 'world_breaker_ach',
    name: '世界破坏者',
    description: '触发终焉之战',
    icon: '☄️',
    hidden: true,
    condition: 'event.count.final_cataclysm >= 1',
    category: 'secret',
  },
  {
    id: 'lucky_star',
    name: '幸运之星',
    description: '运势达到10',
    icon: '🌟',
    hidden: false,
    condition: 'attribute.peak.luk >= 10',
    category: 'attribute',
  },
  {
    id: 'iron_body',
    name: '钢铁之躯',
    description: '体魄达到10',
    icon: '🛡️',
    hidden: false,
    condition: 'attribute.peak.str >= 10',
    category: 'attribute',
  },
  {
    id: 'beauty_supreme',
    name: '绝世容颜',
    description: '魅力达到10',
    icon: '💎',
    hidden: false,
    condition: 'attribute.peak.chr >= 10',
    category: 'attribute',
  },
  {
    id: 'wisdom_peak',
    name: '全知者',
    description: '智慧达到10',
    icon: '👁️',
    hidden: false,
    condition: 'attribute.peak.int >= 10',
    category: 'attribute',
  },
  {
    id: 'longevity',
    name: '长寿之人',
    description: '活到80岁',
    icon: '🕐',
    hidden: false,
    condition: 'lifespan >= 80',
    category: 'life',
  },
  {
    id: 'speedrun',
    name: '速通异世界',
    description: '30岁前完成游戏',
    icon: '⚡',
    hidden: true,
    condition: 'lifespan <= 30',
    category: 'secret',
  },
  {
    id: 'centenarian',
    name: '不老传说',
    description: '属性峰值总和超过60',
    icon: '🏆',
    hidden: true,
    condition: 'attribute.peak.chr + attribute.peak.int + attribute.peak.str + attribute.peak.mny + attribute.peak.spr + attribute.peak.mag + attribute.peak.luk >= 60',
    category: 'secret',
  },
  {
    id: 'completionist',
    name: '全成就',
    description: '解锁所有其他成就',
    icon: '👑',
    hidden: true,
    condition: 'achievement.count >= 14',
    category: 'secret',
  },
]
