import type { WorldAttributeDef } from '../../engine/core/types'

export const attributes: WorldAttributeDef[] = [
  {
    id: 'chr',
    name: '魅力',
    icon: '✨',
    description: '外表与气质，影响社交和恋爱',
    color: '#f472b6',
    min: 0,
    max: 10,
    defaultValue: 0,
    group: 'social',
  },
  {
    id: 'int',
    name: '智慧',
    icon: '📚',
    description: '知识与悟性，影响魔法学习和策略',
    color: '#60a5fa',
    min: 0,
    max: 10,
    defaultValue: 0,
    group: 'mental',
  },
  {
    id: 'str',
    name: '体魄',
    icon: '💪',
    description: '力量与耐力，影响战斗和生存',
    color: '#f87171',
    min: 0,
    max: 10,
    defaultValue: 0,
    group: 'physical',
  },
  {
    id: 'mny',
    name: '家境',
    icon: '💰',
    description: '出身家庭的富裕程度',
    color: '#fbbf24',
    min: 0,
    max: 10,
    defaultValue: 0,
    group: 'social',
  },
  {
    id: 'spr',
    name: '灵魂',
    icon: '🔮',
    description: '精神力与意志力，影响魔力和快乐',
    color: '#a78bfa',
    min: 0,
    max: 10,
    defaultValue: 0,
    group: 'mental',
  },
  {
    id: 'mag',
    name: '魔力',
    icon: '🔥',
    description: '天生魔力亲和度，决定魔法上限',
    color: '#c084fc',
    min: 0,
    max: 10,
    defaultValue: 0,
    group: 'magical',
  },
  {
    id: 'luk',
    name: '运势',
    icon: '🍀',
    description: '天降好运的概率，影响稀有事件',
    color: '#4ade80',
    min: 0,
    max: 10,
    defaultValue: 0,
    group: 'special',
  },
]
