import type { WorldEventDef } from '../../engine/core/types'

export const events: WorldEventDef[] = [
  // ==================== 幼年期（0-6 岁） ====================
  {
    id: 'birth_noble',
    title: '降生贵族',
    description: '你出生在领主的庄园中，第一声啼哭响彻大厅。',
    minAge: 0,
    maxAge: 0,
    weight: 10,
    include: 'attribute.mny >= 6',
    unique: true,
    effects: [],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'birth_common',
    title: '平民之子',
    description: '你出生在一个朴素的农舍中，父亲是一个农夫。',
    minAge: 0,
    maxAge: 0,
    weight: 20,
    include: 'attribute.mny >= 3',
    exclude: 'attribute.mny >= 6',
    unique: true,
    effects: [],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'birth_slums',
    title: '贫民窟的黎明',
    description: '你出生在王国最脏乱的街巷，第一眼看到的是漏水的屋顶。',
    minAge: 0,
    maxAge: 0,
    weight: 15,
    include: 'attribute.mny <= 2',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'magic_burst_baby',
    title: '婴儿的魔力暴走',
    description: '你打了个喷嚏，摇篮旁边的蜡烛全部同时爆炸了。保姆吓得辞职了。',
    minAge: 1,
    maxAge: 3,
    weight: 5,
    include: 'attribute.mag >= 4',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'cry_out',
        title: '大哭',
        description: '你被吓哭了，魔力随着眼泪流淌出来',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 1, description: '魔力 +1' },
          { type: 'set_flag', target: 'emotional_magic', value: 1, description: '感性施法者' },
        ],
      },
      {
        id: 'wave_hands',
        title: '挥舞小手',
        description: '你好奇地挥了挥手，小火球在指尖跳舞',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
          { type: 'modify_hp', target: 'hp', value: -5, description: 'HP -5（烧到手指了）' },
        ],
      },
      {
        id: 'try_control',
        title: '试着控制',
        description: '你竟然本能地尝试控制这股力量！',
        probability: 0.25,
        requireCondition: 'attribute.int >= 4',
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'set_flag', target: 'early_magic_control', value: 1, description: '幼年魔力控制' },
        ],
      },
    ],
    tag: 'magic',
    priority: 'critical',
  },
  {
    id: 'bullied',
    title: '被大孩子欺负',
    description: '村里的大孩子抢走了你的面包，还把你推进泥坑。',
    minAge: 3,
    maxAge: 6,
    weight: 15,
    exclude: 'has.flag.bullied_child',
    effects: [],
    branches: [
      {
        id: 'endure',
        title: '忍气吞声',
        description: '你低着头不说话，等他们走了再从泥坑里爬出来',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（学会隐忍）' },
          { type: 'set_flag', target: 'bullied_child', value: 1, description: '被欺负了' },
        ],
      },
      {
        id: 'seek_help',
        title: '找大人帮忙',
        description: '你跑去找村里的长辈告状',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（学会求助）' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'set_flag', target: 'bullied_child', value: 1, description: '被欺负了' },
        ],
      },
      {
        id: 'fight_back_child',
        title: '试着反抗',
        description: '你握紧拳头冲了上去！虽然没打赢，但他们再也不敢小看你了',
        probability: 0.3,
        requireCondition: 'attribute.str >= 3',
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_hp', target: 'hp', value: -5, description: 'HP -5' },
          { type: 'set_flag', target: 'bullied_child', value: 1, description: '被欺负了' },
          { type: 'set_flag', target: 'fight_back', value: 1, description: '不再忍气吞声' },
        ],
      },
    ],
    tag: 'social',
    priority: 'critical',
  },
  {
    id: 'church_orphan',
    title: '教会的温暖',
    description: '孤儿院的修女们对你格外温柔，教会了你认字。',
    minAge: 4,
    maxAge: 6,
    weight: 10,
    include: 'attribute.mny <= 2',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'fairy_encounter',
    title: '林中的精灵',
    description: '你在森林边缘发现了一只受伤的精灵，你帮它包扎了翅膀。',
    minAge: 5,
    maxAge: 6,
    weight: 3,
    include: 'attribute.luk >= 4 & attribute.spr >= 3',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
      { type: 'modify_attribute', target: 'mag', value: 1, description: '魔力 +1' },
      { type: 'set_flag', target: 'fairy_friend', value: 1, description: '精灵之友' },
    ],
    tag: 'adventure',
    priority: 'major',
  },

  // ==================== 少年期（7-15 岁） ====================
  {
    id: 'magic_academy_notice',
    title: '魔法学院来信',
    description: '一只水晶蝴蝶送来了魔力学院的入学通知。',
    minAge: 7,
    maxAge: 10,
    weight: 8,
    include: 'attribute.mag >= 5',
    exclude: 'has.flag.magic_student',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'enroll_academy',
        title: '入学',
        description: '你踏入了魔法学院的大门，空气中弥漫着魔力的味道',
        probability: 0.6,
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'set_flag', target: 'magic_student', value: 1, description: '成为魔法学生' },
        ],
      },
      {
        id: 'refuse_academy',
        title: '拒绝入学',
        description: '"我不想被关在塔里看书。"你把信塞进了抽屉',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
        ],
      },
    ],
    tag: 'magic',
    priority: 'critical',
  },
  {
    id: 'squire_training',
    title: '侍从修炼',
    description: '你成为了骑士的侍从，每天挥剑一千次。',
    minAge: 10,
    maxAge: 14,
    weight: 12,
    include: 'attribute.str >= 4',
    exclude: 'has.flag.squire',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'train_hard',
        title: '全力修炼',
        description: '你咬牙坚持，手上的茧比谁都厚',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 3, description: '体魄 +3' },
          { type: 'modify_hp', target: 'hp', value: -10, description: 'HP -10（训练受伤）' },
          { type: 'set_flag', target: 'squire', value: 1, description: '侍从修炼（刻苦）' },
        ],
      },
      {
        id: 'slack_off',
        title: '偷懒摸鱼',
        description: '你学会了偷懒的技巧——假装在挥剑，其实在打瞌睡',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1（摸鱼也是一种智慧）' },
          { type: 'set_flag', target: 'squire', value: 1, description: '侍从修炼（摸鱼）' },
        ],
      },
    ],
    tag: 'combat',
    priority: 'critical',
  },
  {
    id: 'first_love',
    title: '初恋的味道',
    description: '邻居家的孩子对你笑了，你的心脏像是被魔法定住了。',
    minAge: 12,
    maxAge: 15,
    weight: 8,
    include: 'attribute.chr >= 5',
    exclude: 'has.flag.first_love',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'confess',
        title: '表白',
        description: '你鼓起勇气递上了一封手写的信',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
          { type: 'set_flag', target: 'first_love', value: 1, description: '初恋（表白）' },
        ],
      },
      {
        id: 'secret_crush',
        title: '暗恋',
        description: '你把这份感情藏在心底，远远地看着对方就好',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（学会思考）' },
          { type: 'set_flag', target: 'first_love', value: 1, description: '初恋（暗恋）' },
        ],
      },
      {
        id: 'give_up',
        title: '放弃',
        description: '"还太早了。"你摇摇头，转身继续练习剑术',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'set_flag', target: 'first_love', value: 1, description: '初恋（放弃）' },
        ],
      },
    ],
    tag: 'romance',
    priority: 'critical',
  },
  {
    id: 'bullied_fight_back',
    title: '反击！',
    description: '曾经欺负你的孩子又来了，这次你揍了他一顿。',
    minAge: 12,
    maxAge: 15,
    weight: 6,
    include: 'attribute.str >= 5',
    exclude: 'has.flag.fight_back',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
      { type: 'set_flag', target: 'fight_back', value: 1, description: '不再忍气吞声' },
    ],
    tag: 'combat',
    priority: 'major',
  },
  {
    id: 'dungeon_explore_1',
    title: '初探地下城',
    description: '你和小伙伴偷偷溜进村外的废弃矿洞，发现了一条地下河。',
    minAge: 13,
    maxAge: 15,
    weight: 7,
    include: 'attribute.str >= 3 | attribute.mag >= 3',
    exclude: 'has.flag.dungeon_first',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
      { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
      { type: 'set_flag', target: 'dungeon_first', value: 1, description: '初次探险' },
    ],
    tag: 'adventure',
    priority: 'major',
  },
  {
    id: 'dragon_awakening',
    title: '龙血觉醒',
    description: '一天夜里你浑身发烫，皮肤下有什么东西在涌动。你的瞳孔变成了竖瞳——龙血在苏醒。',
    minAge: 12,
    maxAge: 14,
    weight: 1,
    include: 'has.talent.dragon_blood',
    effects: [
      { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
      { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
      { type: 'modify_max_hp_bonus', target: 'max_hp', value: 50, description: 'HP上限 +50（龙血强化）' },
      { type: 'set_flag', target: 'dragon_awakened', value: 1, description: '龙血觉醒！' },
    ],
    unique: true,
    tag: 'epic',
    priority: 'major',
  },
  {
    id: 'demon_hunt',
    title: '猎魔骑士的追杀',
    description: '你的魔族血脉被圣教会发现了。三名猎魔骑士在月夜来袭。',
    minAge: 10,
    maxAge: 12,
    weight: 1,
    include: 'has.talent.demon_heritage',
    effects: [],
    branches: [
      {
        id: 'resist_flee',
        title: '抵抗逃亡',
        description: '拼死抵抗后逃入荒野',
        probability: 0.6,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'modify_hp', target: 'hp', value: -20, description: 'HP -20' },
          { type: 'set_flag', target: 'fugitive', value: 1, description: '成为逃犯' },
        ],
      },
      {
        id: 'power_rampage',
        title: '隐藏力量暴走',
        description: '魔族力量突然爆发！',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 3, description: '魔力 +3' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'spr', value: -2, description: '灵魂 -2' },
          { type: 'set_flag', target: 'demon_power', value: 1, description: '魔族之力觉醒' },
        ],
      },
      {
        id: 'friend_protect',
        title: '被朋友保护',
        description: '朋友挡在你面前，替你求情',
        probability: 0.1,
        requireCondition: 'attribute.chr >= 4',
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'set_flag', target: 'has_ally', value: 1, description: '患难之交' },
        ],
      },
    ],
    unique: true,
    tag: 'epic',
    priority: 'critical',
  },
  {
    id: 'reincarnated_memory',
    title: '前世记忆',
    description: '你突然想起了前世的一切——一栋玻璃大厦、一块发光的板子、还有…加班？',
    minAge: 8,
    maxAge: 10,
    weight: 1,
    include: 'has.talent.reincarnated',
    effects: [
      { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2' },
      { type: 'set_flag', target: 'reincarnated', value: 1, description: '前世觉醒' },
    ],
    unique: true,
    tag: 'epic',
    priority: 'major',
  },

  // ==================== 青年期（16-30 岁） ====================
  {
    id: 'guild_join',
    title: '加入冒险者公会',
    description: '你推开公会大门，铜铃叮当作响。"新人？登记表在那儿。"',
    minAge: 16,
    maxAge: 20,
    weight: 15,
    include: 'attribute.str >= 4 | attribute.mag >= 4',
    exclude: 'has.flag.guild_member',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'join_guild',
        title: '加入公会',
        description: '你在登记表上签了名，成为了一名正式冒险者',
        probability: 0.6,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'set_flag', target: 'guild_member', value: 1, description: '成为冒险者' },
        ],
      },
      {
        id: 'solo_adventure',
        title: '独自冒险',
        description: '"我不需要公会。"你转身离开，踏上独自的旅途',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
          { type: 'set_flag', target: 'solo_adventurer', value: 1, description: '独行侠' },
        ],
      },
    ],
    tag: 'adventure',
    priority: 'critical',
  },
  {
    id: 'magic_graduate',
    title: '魔法学院毕业',
    description: '五年苦修终于结束，你拿到了魔法师的毕业证——上面写着"可独立使用3阶以下魔法"。',
    minAge: 20,
    maxAge: 25,
    weight: 5,
    include: 'attribute.int >= 6',
    exclude: 'has.flag.mage_graduate',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
      { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
      { type: 'set_flag', target: 'mage_graduate', value: 1, description: '魔法毕业' },
    ],
    tag: 'magic',
    priority: 'major',
  },
  {
    id: 'first_quest',
    title: '第一个委托',
    description: '公会墙上贴着一张皱巴巴的委托单："灭杀村外骚扰家畜的史莱姆"。报酬：5银币。',
    minAge: 16,
    maxAge: 22,
    weight: 10,
    unique: true,
    effects: [],
    branches: [
      {
        id: 'quest_serious',
        title: '认真完成',
        description: '你仔细调查了史莱姆的出没规律，制定了完美的作战计划',
        probability: 0.6,
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'set_flag', target: 'reliable_adventurer', value: 1, description: '可靠的冒险者' },
        ],
      },
      {
        id: 'quest_slack',
        title: '敷衍了事',
        description: '你随便打了几只史莱姆就回来交差了',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 1, description: '家境 +1' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1（省力也是一种本事）' },
        ],
      },
    ],
    tag: 'adventure',
    priority: 'critical',
  },
  {
    id: 'dragon_slay_attempt',
    title: '讨伐巨龙',
    description: '一头黑龙盘踞在北方的山谷，赏金高得惊人。你决定去试试。',
    minAge: 22,
    maxAge: 35,
    weight: 4,
    include: 'attribute.str >= 7 | attribute.mag >= 7',
    effects: [],
    branches: [
      {
        id: 'dragon_kill',
        title: '正面击杀',
        description: '你与巨龙正面对决！',
        requireCondition: 'attribute.str >= 9 | attribute.mag >= 9',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_attribute', target: 'mny', value: 5, description: '家境 +5' },
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2' },
          { type: 'set_flag', target: 'dragon_slayer', value: 1, description: '屠龙者！' },
        ],
      },
      {
        id: 'dragon_near_death',
        title: '惨胜',
        description: '你赢了，但代价惨重',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_hp', target: 'hp', value: -50, description: 'HP -50' },
          { type: 'modify_attribute', target: 'mny', value: 3, description: '家境 +3' },
          { type: 'set_flag', target: 'near_death', value: 1, description: '濒死体验' },
        ],
      },
      {
        id: 'dragon_defeat',
        title: '被龙击败',
        description: '你败了，但至少活着回来了',
        probability: 0.3,
        effects: [
          { type: 'modify_hp', target: 'hp', value: -80, description: 'HP -80' },
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
          { type: 'set_flag', target: 'dragon_defeated', value: 1, description: '败北' },
        ],
      },
    ],
    unique: true,
    tag: 'epic',
    priority: 'critical',
  },
  {
    id: 'royal_summon',
    title: '皇城的召见',
    description: '一队皇家卫兵出现在你面前。"陛下有请。"',
    minAge: 18,
    maxAge: 25,
    weight: 1,
    include: 'has.talent.royal_lineage',
    effects: [
      { type: 'modify_attribute', target: 'mny', value: 3, description: '家境 +3' },
      { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
      { type: 'set_flag', target: 'royal_recognized', value: 1, description: '皇室认可' },
    ],
    unique: true,
    tag: 'epic',
    priority: 'major',
  },
  {
    id: 'hero_journey_start',
    title: '勇者的旅途',
    description: '圣剑在王座大厅中发出共鸣，飞到了你的手中。"你就是预言中的勇者。"',
    minAge: 16,
    maxAge: 20,
    weight: 1,
    include: 'has.talent.hero_summon',
    effects: [
      { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
      { type: 'modify_attribute', target: 'mag', value: 1, description: '魔力 +1' },
      { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
      { type: 'set_flag', target: 'hero_journey', value: 1, description: '踏上勇者之路' },
    ],
    unique: true,
    tag: 'epic',
    priority: 'major',
  },
  {
    id: 'marry_noble',
    title: '政治联姻',
    description: '你被安排与一位贵族结婚。这在王国中很常见。',
    minAge: 25,
    maxAge: 30,
    weight: 6,
    include: 'attribute.chr >= 6 & attribute.mny >= 5',
    exclude: 'has.flag.married',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'accept_noble_marriage',
        title: '接受联姻',
        description: '你穿上礼服，走上了红毯',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 3, description: '家境 +3' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'set_flag', target: 'married', value: 1, description: '已婚（贵族）' },
        ],
      },
      {
        id: 'refuse_noble_marriage',
        title: '拒绝联姻',
        description: '"我的婚姻不该是筹码。"你毅然回绝',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'set_flag', target: 'refused_marriage', value: 1, description: '拒绝联姻' },
        ],
      },
    ],
    tag: 'romance',
    priority: 'critical',
  },
  {
    id: 'marry_adventurer',
    title: '与冒险者结婚',
    description: '你们在一次地下城探索中相识相知，决定共度余生。',
    minAge: 22,
    maxAge: 30,
    weight: 5,
    include: 'attribute.chr >= 5',
    exclude: 'has.flag.married',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'together_forever',
        title: '在一起',
        description: '你们在星空下交换了誓言',
        probability: 0.6,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'set_flag', target: 'married', value: 1, description: '已婚（冒险者）' },
        ],
      },
      {
        id: 'stay_friends',
        title: '保持友谊',
        description: '"我们更适合做战友。"你们相视一笑',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
          { type: 'set_flag', target: 'true_friend', value: 1, description: '真挚友谊' },
        ],
      },
    ],
    tag: 'romance',
    priority: 'critical',
  },
  {
    id: 'dark_mage_tempt',
    title: '暗黑魔师的诱惑',
    description: '"你想要的…力量，我都有。只要你愿意付出代价。"',
    minAge: 20,
    maxAge: 30,
    weight: 6,
    include: 'attribute.mag >= 5',
    exclude: 'attribute.spr >= 5',
    effects: [],
    branches: [
      {
        id: 'accept_power',
        title: '接受力量',
        description: '你握住了他伸出的手',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 3, description: '魔力 +3' },
          { type: 'modify_attribute', target: 'spr', value: -3, description: '灵魂 -3' },
          { type: 'set_flag', target: 'dark_path', value: 1, description: '踏入暗黑之路' },
        ],
      },
      {
        id: 'reject_fight',
        title: '拒绝并战斗',
        description: '你拔剑迎战！',
        probability: 0.4,
        requireCondition: 'attribute.str >= 5 | attribute.mag >= 7',
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'modify_hp', target: 'hp', value: -20, description: 'HP -20' },
          { type: 'set_flag', target: 'pure_heart', value: 1, description: '纯净之心' },
        ],
      },
      {
        id: 'escape_dark',
        title: '巧妙逃脱',
        description: '你用计策骗过了暗黑魔师，全身而退',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'set_flag', target: 'escaped_dark', value: 1, description: '逃脱诱惑' },
        ],
      },
    ],
    unique: true,
    tag: 'dark',
    priority: 'critical',
  },
  {
    id: 'tavern_brawl',
    title: '酒馆斗殴',
    description: '几杯麦酒下肚，一个兽人对你的长相发表了不当评论。',
    minAge: 18,
    maxAge: 25,
    weight: 12,
    include: 'attribute.str >= 5',
    effects: [
      { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
      { type: 'modify_hp', target: 'hp', value: -10, description: 'HP -10' },
      { type: 'set_flag', target: 'tough_reputation', value: 1, description: '硬汉名声' },
    ],
    tag: 'combat',
    priority: 'minor',
  },
  {
    id: 'fairy_friend_return',
    title: '精灵的报恩',
    description: '当年你救下的精灵回来了，它带来了一颗星光果实。',
    minAge: 18,
    maxAge: 25,
    weight: 2,
    include: 'has.flag.fairy_friend',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
      { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
      { type: 'modify_hp', target: 'hp', value: 30, description: 'HP +30' },
    ],
    tag: 'adventure',
    priority: 'major',
  },

  // ==================== 中年期（31-60 岁） ====================
  {
    id: 'become_lord',
    title: '受封领主',
    description: '因为你的功绩，国王封你为一方领主。',
    minAge: 35,
    maxAge: 50,
    weight: 3,
    include: 'attribute.mny >= 6 & attribute.chr >= 5',
    effects: [
      { type: 'modify_attribute', target: 'mny', value: 3, description: '家境 +3' },
      { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
      { type: 'set_flag', target: 'lord', value: 1, description: '受封领主' },
    ],
    unique: true,
    tag: 'social',
    priority: 'major',
  },
  {
    id: 'master_spell',
    title: '顿悟！魔法真谛',
    description: '你终于理解了魔法的本质——不是操控元素，而是与世界的对话。',
    minAge: 40,
    maxAge: 55,
    weight: 3,
    include: 'attribute.mag >= 8 & attribute.int >= 7',
    effects: [
      { type: 'modify_attribute', target: 'mag', value: 3, description: '魔力 +3' },
      { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2' },
      { type: 'set_flag', target: 'archmage', value: 1, description: '大魔导师！' },
    ],
    unique: true,
    tag: 'magic',
    priority: 'major',
  },
  {
    id: 'student_successor',
    title: '收徒传艺',
    description: '一个年轻人跪在你面前："请收我为徒！"',
    minAge: 35,
    maxAge: 55,
    weight: 8,
    include: 'attribute.str >= 7 | attribute.mag >= 7',
    exclude: 'has.flag.has_student',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
      { type: 'set_flag', target: 'has_student', value: 1, description: '收了徒弟' },
    ],
    tag: 'social',
    priority: 'major',
  },
  {
    id: 'lost_in_dungeon',
    title: '地下城迷失',
    description: '你在深层的地下城中迷路了，黑暗中有什么在注视着你。',
    minAge: 35,
    maxAge: 50,
    weight: 5,
    effects: [
      { type: 'modify_hp', target: 'hp', value: -30, description: 'HP -30', probability: 0.5 },
      { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1', probability: 0.5 },
      { type: 'modify_hp', target: 'hp', value: 20, description: 'HP +20（找到宝藏！）', probability: 0.5 },
      { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1', probability: 0.5 },
      { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1', probability: 0.5 },
    ],
    tag: 'adventure',
    priority: 'minor',
  },
  {
    id: 'war_breaks_out',
    title: '战争爆发',
    description: '魔王军入侵了！所有冒险者被征召。',
    minAge: 40,
    maxAge: 55,
    weight: 5,
    effects: [],
    branches: [
      {
        id: 'war_frontline',
        title: '上前线',
        description: '你冲在最前面',
        requireCondition: 'attribute.str >= 6',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_hp', target: 'hp', value: -40, description: 'HP -40' },
          { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2' },
          { type: 'set_flag', target: 'war_veteran', value: 1, description: '战争老兵' },
        ],
      },
      {
        id: 'war_support',
        title: '后方支援',
        description: '你在后方提供支援',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'set_flag', target: 'healer', value: 1, description: '治愈者' },
        ],
      },
      {
        id: 'war_hero',
        title: '带队突击',
        description: '你带领精锐小队直取敌军主将！',
        requireCondition: 'attribute.chr >= 7 & attribute.str >= 7',
        probability: 0.2,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2' },
          { type: 'modify_hp', target: 'hp', value: -50, description: 'HP -50' },
          { type: 'modify_attribute', target: 'mny', value: 3, description: '家境 +3' },
          { type: 'set_flag', target: 'war_hero', value: 1, description: '战争英雄！' },
        ],
      },
    ],
    unique: true,
    tag: 'epic',
    priority: 'critical',
  },
  {
    id: 'world_breaking_start',
    title: '世界崩坏开始',
    description: '你感到世界在颤抖。不是地震——是世界本身的法则在瓦解。',
    minAge: 50,
    maxAge: 60,
    weight: 1,
    include: 'has.talent.worldbreaker',
    effects: [
      { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
      { type: 'modify_attribute', target: 'mag', value: 3, description: '魔力 +3' },
      { type: 'set_flag', target: 'world_breaking', value: 1, description: '世界崩坏开始' },
    ],
    unique: true,
    tag: 'epic',
    priority: 'major',
  },
  {
    id: 'midlife_crisis',
    title: '中年危机',
    description: '"我这辈子到底在干什么？"你站在悬崖边，看着夕阳发呆。',
    minAge: 40,
    maxAge: 50,
    weight: 10,
    unique: true,
    effects: [],
    branches: [
      {
        id: 'let_go',
        title: '放下执念',
        description: '你深吸一口气，决定放下过去的遗憾',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
          { type: 'modify_hp', target: 'hp', value: 10, description: 'HP +10' },
          { type: 'set_flag', target: 'inner_peace', value: 1, description: '内心平静' },
        ],
      },
      {
        id: 'persist_dream',
        title: '坚持梦想',
        description: '"还没完！"你攥紧拳头，重新燃起了斗志',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'set_flag', target: 'never_give_up', value: 1, description: '永不放弃' },
        ],
      },
    ],
    tag: 'life',
    priority: 'critical',
  },
  {
    id: 'reincarnated_invention',
    title: '前世知识变现',
    description: '你想起前世的配方，调出了一种这个世界从未见过的药剂——可乐。一夜之间风靡王国。',
    minAge: 30,
    maxAge: 40,
    weight: 1,
    include: 'attribute.int >= 6',
    effects: [
      { type: 'modify_attribute', target: 'mny', value: 5, description: '家境 +5' },
      { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
      { type: 'set_flag', target: 'famous_inventor', value: 1, description: '可乐发明者！' },
    ],
    unique: true,
    tag: 'epic',
    priority: 'major',
  },

  // ==================== 老年期（61-80 岁） ====================
  {
    id: 'retirement',
    title: '挂剑归隐',
    description: '你把武器挂在了壁炉上方，决定安度晚年。',
    minAge: 60,
    maxAge: 70,
    weight: 10,
    unique: true,
    effects: [],
    branches: [
      {
        id: 'retire_peaceful',
        title: '归隐山林',
        description: '你买了一座小木屋，在山林间过起了悠闲的日子',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 3, description: '灵魂 +3' },
          { type: 'modify_hp', target: 'hp', value: 20, description: 'HP +20' },
          { type: 'set_flag', target: 'peaceful_retirement', value: 1, description: '安享晚年' },
        ],
      },
      {
        id: 'continue_adventure',
        title: '继续冒险',
        description: '"老夫还没老到走不动路！"你擦亮了剑',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_hp', target: 'hp', value: -20, description: 'HP -20' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'set_flag', target: 'never_retired', value: 1, description: '永不退休' },
        ],
      },
    ],
    tag: 'life',
    priority: 'critical',
  },
  {
    id: 'legend_spread',
    title: '传说的传播',
    description: '吟游诗人们开始传唱你的故事。',
    minAge: 65,
    maxAge: 75,
    weight: 8,
    include: 'attribute.chr >= 7',
    effects: [
      { type: 'modify_attribute', target: 'chr', value: 3, description: '魅力 +3' },
      { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
    ],
    unique: true,
    tag: 'social',
    priority: 'major',
  },
  {
    id: 'final_cataclysm',
    title: '终焉之战',
    description: '天空裂开，混沌涌入。世界需要一个终章。而你，就是执笔之人。',
    minAge: 55,
    maxAge: 65,
    weight: 1,
    include: 'has.talent.worldbreaker',
    effects: [],
    branches: [
      {
        id: 'destroy_world',
        title: '毁灭世界',
        description: '你选择终结一切',
        requireCondition: 'attribute.str >= 10 | attribute.mag >= 10',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: -5, description: '灵魂 -5' },
          { type: 'modify_attribute', target: 'str', value: 3, description: '体魄 +3' },
          { type: 'modify_attribute', target: 'mag', value: 3, description: '魔力 +3' },
          { type: 'set_flag', target: 'world_destroyed', value: 1, description: '世界毁灭者' },
        ],
      },
      {
        id: 'rebuild_world',
        title: '重建世界',
        description: '你选择重塑一切',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 5, description: '灵魂 +5' },
          { type: 'modify_attribute', target: 'int', value: 3, description: '智慧 +3' },
          { type: 'set_flag', target: 'world_rebuilt', value: 1, description: '世界重建者' },
        ],
      },
      {
        id: 'become_god',
        title: '成为新世界的神',
        description: '你超越了凡人的界限',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2' },
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2' },
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
          { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
          { type: 'modify_attribute', target: 'luk', value: 2, description: '运势 +2' },
          { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2' },
          { type: 'set_flag', target: 'became_god', value: 1, description: '新世界的神！' },
        ],
      },
    ],
    unique: true,
    tag: 'epic',
    priority: 'critical',
  },
  {
    id: 'peaceful_end',
    title: '平静的终章',
    description: '你坐在门廊的摇椅上，看着孙辈们在花园里奔跑。夕阳很美。',
    minAge: 70,
    maxAge: 80,
    weight: 12,
    include: 'attribute.spr >= 5',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'spr', value: 3, description: '灵魂 +3' },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'magic_breakthrough_final',
    title: '最后的魔法',
    description: '你感到自己的魔力在消散，于是决定将毕生所学注入最后一道法术。',
    minAge: 70,
    maxAge: 80,
    weight: 4,
    include: 'attribute.mag >= 9',
    effects: [
      { type: 'modify_attribute', target: 'mag', value: 5, description: '魔力 +5（最后一刻的辉煌）' },
      { type: 'modify_hp', target: 'hp', value: -30, description: 'HP -30' },
    ],
    unique: true,
    tag: 'magic',
    priority: 'major',
  },
]
