import type { WorldEventDef } from '../../engine/core/types'

export const events: WorldEventDef[] = [
  // ==================== 幼年期（0-6 岁） ====================
  {
    id: 'birth_noble',
    title: '降生贵族',
    description: '你出生在领主的庄园中，第一声啼哭响彻大厅。',
    minAge: 0,
    maxAge: 0,
    weight: 10,
    include: 'attribute.mny >= 10',
    unique: true,
    effects: [],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'birth_common',
    title: '平民之子',
    description: '你出生在一个朴素的农舍中，父亲是一个农夫。',
    minAge: 0,
    maxAge: 0,
    weight: 20,
    include: 'attribute.mny >= 4',
    exclude: 'attribute.mny >= 10',
    unique: true,
    effects: [],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'birth_slums',
    title: '贫民窟的黎明',
    description: '你出生在王国最脏乱的街巷，第一眼看到的是漏水的屋顶。',
    minAge: 0,
    maxAge: 0,
    weight: 15,
    include: 'attribute.mny <= 2',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'magic_burst_baby',
    title: '婴儿的魔力暴走',
    description: '你打了个喷嚏，摇篮旁边的蜡烛全部同时爆炸了。保姆吓得辞职了。',
    minAge: 1,
    maxAge: 3,
    weight: 5,
    include: 'attribute.mag >= 6',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'cry_out',
        title: '大哭',
        description: '你被吓哭了，魔力随着眼泪流淌出来',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 1, description: '魔力 +1' },
          { type: 'set_flag', target: 'emotional_magic', value: 1, description: '感性施法者' },
        ],
      },
      {
        id: 'wave_hands',
        title: '挥舞小手',
        description: '你好奇地挥了挥手，小火球在指尖跳舞',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
          { type: 'modify_hp', target: 'hp', value: -5, description: 'HP -5（烧到手指了）' },
        ],
      },
      {
        id: 'try_control',
        title: '试着控制',
        description: '你竟然本能地尝试控制这股力量！',
        probability: 0.25,
        requireCondition: 'attribute.int >= 5',
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'set_flag', target: 'early_magic_control', value: 1, description: '幼年魔力控制' },
        ],
      },
    ],
    tag: 'magic',
    priority: 'major',
  },
  {
    id: 'bullied',
    title: '被大孩子欺负',
    description: '村里的大孩子抢走了你的面包，还把你推进泥坑。',
    minAge: 3,
    maxAge: 6,
    weight: 5,
    exclude: 'has.flag.bullied_child',
    effects: [],
    branches: [
      {
        id: 'endure',
        title: '忍气吞声',
        description: '你低着头不说话，等他们走了再从泥坑里爬出来',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（学会隐忍）' },
          { type: 'set_flag', target: 'bullied_child', value: 1, description: '被欺负了' },
          { type: 'set_flag', target: 'timid', value: 1, description: '胆怯' },
        ],
      },
      {
        id: 'seek_help',
        title: '找大人帮忙',
        description: '你跑去找村里的长辈告状',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（学会求助）' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'set_flag', target: 'bullied_child', value: 1, description: '被欺负了' },
        ],
      },
      {
        id: 'fight_back_child',
        title: '试着反抗',
        description: '你握紧拳头冲了上去！',
        probability: 0.3,
        requireCondition: 'attribute.str >= 3',
        riskCheck: {
          attribute: 'str',
          difficulty: 4,
          scale: 2,
        },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_hp', target: 'hp', value: -3, description: 'HP -3' },
          { type: 'set_flag', target: 'bullied_child', value: 1, description: '被欺负了' },
          { type: 'set_flag', target: 'fight_back', value: 1, description: '不再忍气吞声' },
        ],
        failureEffects: [
          { type: 'modify_hp', target: 'hp', value: -15, description: 'HP -15' },
          { type: 'set_flag', target: 'bullied_child', value: 1, description: '被欺负了' },
        ],
        successText: '虽然挨了几拳，但你让他们知道你不是好惹的！',
        failureText: '你冲了上去，但对方太壮了...你被打得鼻青脸肿',
      },
    ],
    tag: 'social',
    priority: 'major',
    unique: true,
  },
  {
    id: 'church_orphan',
    title: '教会的温暖',
    description: '孤儿院的修女们对你格外温柔，教会了你认字。',
    minAge: 4,
    maxAge: 6,
    weight: 10,
    include: 'attribute.mny <= 2',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'fairy_encounter',
    title: '林中的精灵',
    description: '你在森林边缘发现了一只受伤的精灵，你帮它包扎了翅膀。',
    minAge: 5,
    maxAge: 6,
    weight: 3,
    include: 'attribute.luk >= 6 & attribute.spr >= 4',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
      { type: 'modify_attribute', target: 'mag', value: 1, description: '魔力 +1' },
      { type: 'set_flag', target: 'fairy_friend', value: 1, description: '精灵之友' },
    ],
    tag: 'adventure',
    priority: 'major',
  },
  {
    id: 'bullied_repeat',
    title: '他们又来了',
    description: '欺负你的大孩子又出现了，这次他们把你堵在了小巷里。看来上次的隐忍被当成了软弱。',
    minAge: 4,
    maxAge: 8,
    weight: 8,
    include: 'has.flag.timid',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'endure_again',
        title: '继续忍耐',
        description: '你咬着嘴唇，等他们心满意足地离开',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
          { type: 'set_flag', target: 'timid_deep', value: 1, description: '深度胆怯' },
        ],
      },
      {
        id: 'tell_parents',
        title: '告诉父母',
        description: '这次你决定不再独自承受，跑回家告诉了父母',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（学会求助）' },
          { type: 'set_flag', target: 'parental_help', value: 1, description: '父母介入' },
        ],
      },
    ],
    tag: 'social',
    priority: 'major',
  },
  {
    id: 'stand_up_moment',
    title: '不再忍耐',
    description: '那些大孩子又来挑衅了。但这次，你心里有什么东西碎裂了——取而代之的是一股从未有过的勇气。',
    minAge: 6,
    maxAge: 10,
    weight: 5,
    include: 'has.flag.timid',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'fight_back_brave',
        title: '正面反击',
        description: '"够了！"你攥紧拳头站了起来，眼中是连你自己都陌生的怒火',
        probability: 0.5,
        riskCheck: {
          attribute: 'str',
          difficulty: 5,
          scale: 2,
        },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'set_flag', target: 'brave', value: 1, description: '变得勇敢' },
        ],
        failureEffects: [
          { type: 'modify_hp', target: 'hp', value: -8, description: 'HP -8' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（至少你尝试了）' },
        ],
        successText: '你一拳打在了带头那人的鼻子上！他们惊愕地看着你，再也不敢来犯',
        failureText: '你还是打不过，但你眼中的勇气让他们犹豫了...暂时',
      },
      {
        id: 'seek_help_smart',
        title: '寻求帮助',
        description: '你找到了村长，把一切都告诉了他',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（用脑子解决问题）' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'set_flag', target: 'smart_seeker', value: 1, description: '善于求助' },
        ],
      },
    ],
    tag: 'social',
    priority: 'major',
  },
  {
    id: 'noble_kid_revenge',
    title: '权贵的孩子',
    description: '一个穿着华丽的同龄孩子当街抢走了你的东西，周围的人视而不见——大家都知道他父亲是谁。',
    minAge: 5,
    maxAge: 9,
    weight: 1,
    unique: true,
    effects: [],
    branches: [
      {
        id: 'swallow_pride',
        title: '默默忍耐',
        description: '你知道得罪不起权贵，低下头认了错',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
          { type: 'set_flag', target: 'noble_grudge', value: 1, description: '对权贵的怨恨' },
        ],
      },
      {
        id: 'stand_ground',
        title: '据理力争',
        description: '"是他先欺负我的！"你不卑不亢地直视那权贵的眼睛',
        probability: 0.35,
        riskCheck: {
          attribute: 'chr',
          difficulty: 6,
          scale: 2,
        },
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2' },
          { type: 'set_flag', target: 'noble_conflict', value: 1, description: '与权贵冲突' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
          { type: 'modify_hp', target: 'hp', value: -10, description: 'HP -10' },
          { type: 'set_flag', target: 'noble_conflict', value: 1, description: '与权贵冲突' },
        ],
        successText: '权贵被你的气势镇住了，悻悻离去。你赢得了村民的尊敬',
        failureText: '权贵冷笑一声，把你推倒在地..."不知天高地厚"',
      },
      {
        id: 'report_authority',
        title: '告到更高层',
        description: '你越过了那权贵，直接去找了领主的代理人',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'set_flag', target: 'justice_seek', value: 1, description: '追求正义' },
        ],
      },
    ],
    tag: 'social',
    priority: 'critical',
  },

  // ==================== 少年期（7-15 岁） ====================
  {
    id: 'magic_academy_notice',
    title: '魔法学院来信',
    description: '一只水晶蝴蝶送来了魔力学院的入学通知。',
    minAge: 7,
    maxAge: 10,
    weight: 8,
    include: 'attribute.mag >= 8',
    exclude: 'has.flag.magic_student',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'enroll_academy',
        title: '入学',
        description: '你踏入了魔法学院的大门，空气中弥漫着魔力的味道',
        probability: 0.6,
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'set_flag', target: 'magic_student', value: 1, description: '成为魔法学生' },
        ],
      },
      {
        id: 'refuse_academy',
        title: '拒绝入学',
        description: '"我不想被关在塔里看书。"你把信塞进了抽屉',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
        ],
      },
    ],
    tag: 'magic',
    priority: 'critical',
  },
  {
    id: 'magic_exam',
    title: '魔法期末考试',
    description: '学院年终考核，考官宣布：不及格者将被劝退。',
    minAge: 10,
    maxAge: 13,
    weight: 6,
    include: 'has.flag.magic_student',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'study_hard',
        title: '全力备考',
        description: '你通宵达旦地复习，把每一个咒语都背得滚瓜烂熟',
        probability: 0.5,
        riskCheck: {
          attribute: 'int',
          difficulty: 10,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2' },
          { type: 'modify_attribute', target: 'mag', value: 1, description: '魔力 +1' },
          { type: 'set_flag', target: 'magic_top_student', value: 1, description: '魔法优等生' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'modify_hp', target: 'hp', value: -5, description: 'HP -5（熬夜伤身）' },
        ],
        successText: '你拿到了全年级第三名！教授对你刮目相看',
        failureText: '你拼尽全力，勉强及格...下次要更努力',
      },
      {
        id: 'cheat_exam',
        title: '考前突击',
        description: '你在袖子里藏了一张小抄...希望能蒙混过关',
        probability: 0.3,
        riskCheck: {
          attribute: 'luk',
          difficulty: 8,
          scale: 2,
        },
        effects: [
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1（运气真好）' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'spr', value: -2, description: '灵魂 -2（被抓到作弊）' },
          { type: 'modify_attribute', target: 'chr', value: -1, description: '魅力 -1' },
        ],
        successText: '居然蒙混过关了！但你心里知道这不是长久之计',
        failureText: '考官当场抓住了你的小抄...你被罚站了一整天',
      },
      {
        id: 'natural_talent',
        title: '靠天赋',
        description: '你凭借与生俱来的魔力直觉应对考试',
        probability: 0.2,
        requireCondition: 'attribute.mag >= 12',
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
          { type: 'set_flag', target: 'magic_natural', value: 1, description: '天赋型法师' },
        ],
      },
    ],
    tag: 'magic',
    priority: 'major',
  },
  {
    id: 'squire_training',
    title: '侍从修炼',
    description: '你成为了骑士的侍从，每天挥剑一千次。',
    minAge: 10,
    maxAge: 14,
    weight: 3,
    include: 'attribute.str >= 4',
    exclude: 'has.flag.squire',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'train_hard',
        title: '全力修炼',
        description: '你咬牙坚持，手上的茧比谁都厚',
        probability: 0.5,
        riskCheck: {
          attribute: 'str',
          difficulty: 8,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 3, description: '体魄 +3' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'set_flag', target: 'squire', value: 1, description: '侍从修炼（刻苦）' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_hp', target: 'hp', value: -10, description: 'HP -10（训练受伤）' },
          { type: 'set_flag', target: 'squire', value: 1, description: '侍从修炼（刻苦）' },
        ],
        successText: '训练师的目光从轻视变成了赞许',
        failureText: '你拼尽了全力，但还是差了一点...明天继续',
      },
      {
        id: 'slack_off',
        title: '偷懒摸鱼',
        description: '你学会了偷懒的技巧——假装在挥剑，其实在打瞌睡',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1（摸鱼也是一种智慧）' },
          { type: 'set_flag', target: 'squire', value: 1, description: '侍从修炼（摸鱼）' },
        ],
      },
    ],
    tag: 'combat',
    priority: 'major',
  },
  {
    id: 'first_love',
    title: '初恋的味道',
    description: '邻居家的孩子对你笑了，你的心脏像是被魔法定住了。',
    minAge: 12,
    maxAge: 15,
    weight: 8,
    include: 'attribute.chr >= 8',
    exclude: 'has.flag.first_love',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'confess',
        title: '表白',
        description: '你鼓起勇气递上了一封手写的信',
        probability: 0.35,
        riskCheck: {
          attribute: 'chr',
          difficulty: 8,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2' },
          { type: 'set_flag', target: 'first_love', value: 1, description: '初恋（表白成功）' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
          { type: 'set_flag', target: 'heartbroken', value: 1, description: '失恋了' },
        ],
        successText: 'TA红着脸点了点头...',
        failureText: 'TA笑了笑说...我们还是做朋友吧',
      },
      {
        id: 'secret_crush',
        title: '暗恋',
        description: '你把这份感情藏在心底，远远地看着对方就好',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（学会思考）' },
          { type: 'set_flag', target: 'first_love', value: 1, description: '初恋（暗恋）' },
        ],
      },
      {
        id: 'give_up',
        title: '放弃',
        description: '"还太早了。"你摇摇头，转身继续练习剑术',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'set_flag', target: 'first_love', value: 1, description: '初恋（放弃）' },
        ],
      },
    ],
    tag: 'romance',
    priority: 'major',
  },
  {
    id: 'bullied_fight_back',
    title: '反击！',
    description: '曾经欺负你的孩子又来了，这次你揍了他一顿。',
    minAge: 12,
    maxAge: 15,
    weight: 6,
    include: 'attribute.str >= 6',
    exclude: 'has.flag.fight_back',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
      { type: 'set_flag', target: 'fight_back', value: 1, description: '不再忍气吞声' },
    ],
    tag: 'combat',
    priority: 'major',
  },
  {
    id: 'dungeon_explore_1',
    title: '初探地下城',
    description: '你和小伙伴偷偷溜进村外的废弃矿洞，发现了一条地下河。',
    minAge: 13,
    maxAge: 15,
    weight: 7,
    include: 'attribute.str >= 3 | attribute.mag >= 4',
    exclude: 'has.flag.dungeon_first',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'explore_deep',
        title: '深入探索',
        description: '你决定沿着地下河往深处走，也许能发现什么宝物',
        probability: 0.5,
        riskCheck: {
          attribute: 'str',
          difficulty: 8,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
          { type: 'set_flag', target: 'dungeon_first', value: 1, description: '初次探险（深入）' },
          { type: 'set_flag', target: 'dungeon_veteran', value: 1, description: '地下城老手' },
        ],
        failureEffects: [
          { type: 'modify_hp', target: 'hp', value: -25, description: 'HP -25（掉进暗河）' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（吃一堑长一智）' },
          { type: 'set_flag', target: 'dungeon_first', value: 1, description: '初次探险（失败）' },
          { type: 'set_flag', target: 'dungeon_injured', value: 1, description: '探险受伤' },
        ],
        successText: '你在河的尽头发现了一处隐藏的宝藏室！',
        failureText: '脚下一滑，你掉进了暗河...好不容易才爬上来',
      },
      {
        id: 'explore_cautious',
        title: '谨慎前行',
        description: '矿洞里太黑了，还是只在入口附近看看吧',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
          { type: 'set_flag', target: 'dungeon_first', value: 1, description: '初次探险' },
        ],
      },
    ],
    tag: 'adventure',
    priority: 'minor',
  },
  {
    id: 'recovery_period',
    title: '伤愈期',
    description: '地下城的伤还没好全，你被迫在家休养。窗外的阳光照在身上，你开始思考很多事。',
    minAge: 14,
    maxAge: 16,
    weight: 7,
    include: 'has.flag.dungeon_injured',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'rest_well',
        title: '安心养伤',
        description: '你决定好好休养，趁这个时间读了一些书',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'modify_hp', target: 'hp', value: 5, description: 'HP +5（充分休养）' },
        ],
      },
      {
        id: 'secret_training',
        title: '偷偷锻炼',
        description: '趁着没人注意，你在房间里做俯卧撑和深蹲',
        probability: 0.5,
        riskCheck: {
          attribute: 'str',
          difficulty: 8,
          scale: 2,
        },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_hp', target: 'hp', value: -5, description: 'HP -5（伤口裂开了）' },
        ],
        failureEffects: [
          { type: 'modify_hp', target: 'hp', value: -15, description: 'HP -15（伤势加重）' },
        ],
        successText: '你的努力没有白费，伤愈后的你比受伤前更强了！',
        failureText: '伤口又裂开了...你被骂了一顿',
      },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'knight_examination',
    title: '骑士考核',
    description: '经过数年的侍从修炼，骑士团终于给了你一个正式考核的机会。通过，你就是一名真正的骑士。',
    minAge: 15,
    maxAge: 18,
    weight: 6,
    include: 'has.flag.squire',
    exclude: 'has.flag.magic_student',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'knight_pass',
        title: '全力应考',
        description: '你回忆着这些年所有的训练，剑术、骑术、礼仪——一切为了今天',
        probability: 0.6,
        riskCheck: {
          attribute: 'str',
          difficulty: 12,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'set_flag', target: 'knight', value: 1, description: '正式骑士！' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'set_flag', target: 'squire_failed', value: 1, description: '骑士考核失败' },
        ],
        successText: '骑士团长将佩剑放在你肩上："从今天起，你就是一名骑士了。"',
        failureText: '你在骑术环节失误了...团长叹了口气："明年再来吧。"',
      },
      {
        id: 'knight_clever',
        title: '以智取胜',
        description: '你发现考核不只是看力量——策略和应变同样重要',
        probability: 0.2,
        requireCondition: 'attribute.int >= 10',
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'set_flag', target: 'knight', value: 1, description: '正式骑士（智将型）' },
        ],
      },
      {
        id: 'knight_give_up',
        title: '主动放弃',
        description: '"也许骑士之路不适合我。"你放下佩剑，选择了另一条路',
        probability: 0.2,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'set_flag', target: 'squire_failed', value: 1, description: '放弃骑士之路' },
        ],
      },
    ],
    tag: 'combat',
    priority: 'major',
  },
  {
    id: 'merchant_apprentice',
    title: '商人的嗅觉',
    description: '一位路过村子的旅行商人注意到了你。"小家伙，你有没有兴趣学做生意？"',
    minAge: 14,
    maxAge: 20,
    weight: 6,
    include: 'attribute.chr >= 8 | attribute.mny >= 8',
    exclude: 'has.flag.magic_student | has.flag.knight',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'accept_merchant',
        title: '拜师学商',
        description: '"比挥剑有趣多了！"你跟着商人踏上了旅途',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'set_flag', target: 'merchant_apprentice', value: 1, description: '商人学徒' },
        ],
      },
      {
        id: 'refuse_merchant',
        title: '婉拒邀请',
        description: '"谢谢您的好意，但我有自己的路要走。"',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
        ],
      },
    ],
    tag: 'social',
    priority: 'critical',
  },
  {
    id: 'dragon_awakening',
    title: '龙血觉醒',
    description: '一天夜里你浑身发烫，皮肤下有什么东西在涌动。你的瞳孔变成了竖瞳——龙血在苏醒。',
    minAge: 12,
    maxAge: 14,
    weight: 1,
    include: 'has.talent.dragon_blood',
    effects: [
      { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
      { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
      { type: 'modify_max_hp_bonus', target: 'max_hp', value: 50, description: 'HP上限 +50（龙血强化）' },
      { type: 'set_flag', target: 'dragon_awakened', value: 1, description: '龙血觉醒！' },
    ],
    unique: true,
    tag: 'epic',
    priority: 'major',
  },
  {
    id: 'demon_hunt',
    title: '猎魔骑士的追杀',
    description: '你的魔族血脉被圣教会发现了。三名猎魔骑士在月夜来袭。',
    minAge: 10,
    maxAge: 12,
    weight: 1,
    include: 'has.talent.demon_heritage',
    effects: [],
    branches: [
      {
        id: 'resist_flee',
        title: '抵抗逃亡',
        description: '拼死抵抗后逃入荒野',
        probability: 0.6,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'modify_hp', target: 'hp', value: -30, description: 'HP -30' },
          { type: 'set_flag', target: 'fugitive', value: 1, description: '成为逃犯' },
        ],
      },
      {
        id: 'power_rampage',
        title: '隐藏力量暴走',
        description: '魔族力量突然爆发！',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 3, description: '魔力 +3' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'spr', value: -2, description: '灵魂 -2' },
          { type: 'set_flag', target: 'demon_power', value: 1, description: '魔族之力觉醒' },
        ],
      },
      {
        id: 'friend_protect',
        title: '被朋友保护',
        description: '朋友挡在你面前，替你求情',
        probability: 0.1,
        requireCondition: 'attribute.chr >= 5',
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'set_flag', target: 'has_ally', value: 1, description: '患难之交' },
        ],
      },
    ],
    unique: true,
    tag: 'epic',
    priority: 'critical',
  },
  {
    id: 'reincarnated_memory',
    title: '前世记忆',
    description: '你突然想起了前世的一切——一栋玻璃大厦、一块发光的板子、还有…加班？',
    minAge: 8,
    maxAge: 10,
    weight: 1,
    include: 'has.talent.reincarnated',
    effects: [
      { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2' },
      { type: 'set_flag', target: 'reincarnated', value: 1, description: '前世觉醒' },
    ],
    unique: true,
    tag: 'epic',
    priority: 'major',
  },

  // ==================== 青年期（16-30 岁） ====================
  {
    id: 'guild_join',
    title: '加入冒险者公会',
    description: '你推开公会大门，铜铃叮当作响。"新人？登记表在那儿。"',
    minAge: 16,
    maxAge: 20,
    weight: 15,
    include: 'attribute.str >= 4 | attribute.mag >= 6',
    exclude: 'has.flag.guild_member',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'join_guild',
        title: '加入公会',
        description: '你在登记表上签了名，成为了一名正式冒险者',
        probability: 0.6,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'set_flag', target: 'guild_member', value: 1, description: '成为冒险者' },
        ],
      },
      {
        id: 'solo_adventure',
        title: '独自冒险',
        description: '"我不需要公会。"你转身离开，踏上独自的旅途',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
          { type: 'set_flag', target: 'solo_adventurer', value: 1, description: '独行侠' },
        ],
      },
    ],
    tag: 'adventure',
    priority: 'major',
  },
  {
    id: 'magic_graduate',
    title: '魔法学院毕业',
    description: '五年苦修终于结束，你拿到了魔法师的毕业证——上面写着"可独立使用3阶以下魔法"。',
    minAge: 20,
    maxAge: 25,
    weight: 5,
    include: 'has.flag.magic_student & attribute.int >= 10',
    exclude: 'has.flag.mage_graduate',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
      { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
      { type: 'set_flag', target: 'mage_graduate', value: 1, description: '魔法毕业' },
    ],
    tag: 'magic',
    priority: 'major',
  },
  {
    id: 'first_quest',
    title: '第一个委托',
    description: '公会墙上贴着一张皱巴巴的委托单："灭杀村外骚扰家畜的史莱姆"。报酬：5银币。',
    minAge: 16,
    maxAge: 22,
    weight: 3,
    unique: true,
    effects: [],
    branches: [
      {
        id: 'quest_serious',
        title: '认真完成',
        description: '你仔细调查了史莱姆的出没规律，制定了完美的作战计划',
        probability: 0.6,
        riskCheck: {
          attribute: 'str',
          difficulty: 12,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'mny', value: 3, description: '家境 +3' },
          { type: 'set_flag', target: 'quest_victory', value: 1, description: '首战告捷' },
        ],
        failureEffects: [
          { type: 'modify_hp', target: 'hp', value: -20, description: 'HP -20' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
        ],
        successText: '任务完成！公会会长拍了拍你的肩膀',
        failureText: '任务失败了...你狼狈地逃回了公会',
      },
      {
        id: 'quest_slack',
        title: '敷衍了事',
        description: '你随便打了几只史莱姆就回来交差了',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 1, description: '家境 +1' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1（省力也是一种本事）' },
        ],
      },
    ],
    tag: 'adventure',
    priority: 'major',
  },
  {
    id: 'dragon_slay_attempt',
    title: '讨伐巨龙',
    description: '一头黑龙盘踞在北方的山谷，赏金高得惊人。你决定去试试。',
    minAge: 22,
    maxAge: 35,
    weight: 4,
    include: 'attribute.str >= 14 | attribute.mag >= 14',
    effects: [],
    branches: [
      {
        id: 'dragon_kill',
        title: '正面击杀',
        description: '你与巨龙正面对决！',
        requireCondition: 'attribute.str >= 18 | attribute.mag >= 18',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_attribute', target: 'mny', value: 5, description: '家境 +5' },
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2' },
          { type: 'set_flag', target: 'dragon_slayer', value: 1, description: '屠龙者！' },
        ],
      },
      {
        id: 'dragon_near_death',
        title: '惨胜',
        description: '你赢了，但代价惨重',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_hp', target: 'hp', value: -50, description: 'HP -50' },
          { type: 'modify_attribute', target: 'mny', value: 3, description: '家境 +3' },
          { type: 'set_flag', target: 'near_death', value: 1, description: '濒死体验' },
        ],
      },
      {
        id: 'dragon_defeat',
        title: '被龙击败',
        description: '你败了，但至少活着回来了',
        probability: 0.3,
        effects: [
          { type: 'modify_hp', target: 'hp', value: -80, description: 'HP -80' },
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
          { type: 'set_flag', target: 'dragon_defeated', value: 1, description: '败北' },
        ],
      },
    ],
    unique: true,
    tag: 'epic',
    priority: 'critical',
  },
  {
    id: 'royal_summon',
    title: '皇城的召见',
    description: '一队皇家卫兵出现在你面前。"陛下有请。"',
    minAge: 18,
    maxAge: 25,
    weight: 1,
    include: 'has.talent.royal_lineage',
    effects: [
      { type: 'modify_attribute', target: 'mny', value: 3, description: '家境 +3' },
      { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
      { type: 'set_flag', target: 'royal_recognized', value: 1, description: '皇室认可' },
    ],
    unique: true,
    tag: 'epic',
    priority: 'major',
  },
  {
    id: 'hero_journey_start',
    title: '勇者的旅途',
    description: '圣剑在王座大厅中发出共鸣，飞到了你的手中。"你就是预言中的勇者。"',
    minAge: 16,
    maxAge: 20,
    weight: 1,
    include: 'has.talent.hero_summon',
    effects: [
      { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
      { type: 'modify_attribute', target: 'mag', value: 1, description: '魔力 +1' },
      { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
      { type: 'set_flag', target: 'hero_journey', value: 1, description: '踏上勇者之路' },
    ],
    unique: true,
    tag: 'epic',
    priority: 'major',
  },
  {
    id: 'marry_noble',
    title: '政治联姻',
    description: '你被安排与一位贵族结婚。这在王国中很常见。',
    minAge: 25,
    maxAge: 30,
    weight: 6,
    include: 'attribute.chr >= 10 & attribute.mny >= 8',
    exclude: 'has.flag.married',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'accept_noble_marriage',
        title: '接受联姻',
        description: '你穿上礼服，走上了红毯',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 3, description: '家境 +3' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'set_flag', target: 'married', value: 1, description: '已婚（贵族）' },
        ],
      },
      {
        id: 'refuse_noble_marriage',
        title: '拒绝联姻',
        description: '"我的婚姻不该是筹码。"你毅然回绝',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'set_flag', target: 'refused_marriage', value: 1, description: '拒绝联姻' },
        ],
      },
    ],
    tag: 'romance',
    priority: 'critical',
  },
  {
    id: 'marry_adventurer',
    title: '与冒险者结婚',
    description: '你们在一次地下城探索中相识相知，决定共度余生。',
    minAge: 22,
    maxAge: 30,
    weight: 5,
    include: 'attribute.chr >= 8',
    exclude: 'has.flag.married',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'together_forever',
        title: '在一起',
        description: '你们在星空下交换了誓言',
        probability: 0.6,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'set_flag', target: 'married', value: 1, description: '已婚（冒险者）' },
        ],
      },
      {
        id: 'stay_friends',
        title: '保持友谊',
        description: '"我们更适合做战友。"你们相视一笑',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
          { type: 'set_flag', target: 'true_friend', value: 1, description: '真挚友谊' },
        ],
      },
    ],
    tag: 'romance',
    priority: 'critical',
  },
  {
    id: 'dark_mage_tempt',
    title: '暗黑魔师的诱惑',
    description: '"你想要的…力量，我都有。只要你愿意付出代价。"',
    minAge: 20,
    maxAge: 30,
    weight: 6,
    include: 'attribute.mag >= 8',
    exclude: 'attribute.spr >= 8',
    effects: [],
    branches: [
      {
        id: 'accept_power',
        title: '接受力量',
        description: '你握住了他伸出的手',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 3, description: '魔力 +3' },
          { type: 'modify_attribute', target: 'spr', value: -3, description: '灵魂 -3' },
          { type: 'set_flag', target: 'dark_path', value: 1, description: '踏入暗黑之路' },
          { type: 'set_flag', target: 'soul_corrupted', value: 1, description: '灵魂被侵蚀' },
        ],
      },
      {
        id: 'reject_fight',
        title: '拒绝并战斗',
        description: '你拔剑迎战！',
        probability: 0.4,
        requireCondition: 'attribute.str >= 6 | attribute.mag >= 14',
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'modify_hp', target: 'hp', value: -20, description: 'HP -20' },
          { type: 'set_flag', target: 'pure_heart', value: 1, description: '纯净之心' },
        ],
      },
      {
        id: 'escape_dark',
        title: '巧妙逃脱',
        description: '你用计策骗过了暗黑魔师，全身而退',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'set_flag', target: 'escaped_dark', value: 1, description: '逃脱诱惑' },
        ],
      },
    ],
    unique: true,
    tag: 'dark',
    priority: 'critical',
  },
  {
    id: 'magic_duel',
    title: '学院决斗赛',
    description: '一年一度的魔法决斗赛开始了。你的对手是高年级的学长——据说他已经能使用4阶魔法。',
    minAge: 15,
    maxAge: 20,
    weight: 5,
    include: 'has.flag.magic_student',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'duel_fight',
        title: '全力应战',
        description: '你调整呼吸，凝聚全身魔力。不管结果如何，这是证明自己的时刻',
        probability: 0.5,
        riskCheck: {
          attribute: 'mag',
          difficulty: 14,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'set_flag', target: 'duel_champion', value: 1, description: '决斗冠军' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'mag', value: 1, description: '魔力 +1（败中学习）' },
          { type: 'modify_hp', target: 'hp', value: -15, description: 'HP -15' },
        ],
        successText: '你的火球术完美命中！全场沸腾，你创造了学院历史——第一个打败高年级的新生！',
        failureText: '你尽力了，但差距还是太大了...不过你的表现赢得了教授们的认可',
      },
      {
        id: 'duel_forfeit',
        title: '弃权旁观',
        description: '你决定不参加决斗，而是在场边仔细观察每一个选手的技巧',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2（观察学习）' },
        ],
      },
      {
        id: 'duel_trick',
        title: '用计取胜',
        description: '你决定不靠蛮力，而是用策略赢得比赛',
        probability: 0.2,
        requireCondition: 'attribute.int >= 12',
        riskCheck: {
          attribute: 'int',
          difficulty: 14,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'set_flag', target: 'duel_champion', value: 1, description: '决斗冠军（智取胜）' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1（计策被识破）' },
        ],
        successText: '你用巧妙的障眼法迷惑了对手，在所有人目瞪口呆中赢得了胜利！',
        failureText: '对手看穿了你的把戏..."有意思的尝试，但太嫩了"',
      },
    ],
    tag: 'magic',
    priority: 'critical',
  },
  {
    id: 'dark_mage_choice',
    title: '禁忌知识的召唤',
    description: '在学院禁书区的深处，一本泛着紫光的书似乎在呼唤你。你已经是高年级生了，对魔法的理解远超同辈——但有些知识是被封印的。',
    minAge: 20,
    maxAge: 30,
    weight: 4,
    include: 'has.flag.magic_student & attribute.mag >= 15',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'open_forbidden',
        title: '翻开禁书',
        description: '"知识不应有禁区。"你翻开了那本书',
        probability: 0.3,
        riskCheck: {
          attribute: 'spr',
          difficulty: 16,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 4, description: '魔力 +4（禁忌之力）' },
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2' },
          { type: 'set_flag', target: 'dark_mage', value: 1, description: '暗黑法师' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'mag', value: 3, description: '魔力 +3' },
          { type: 'modify_attribute', target: 'spr', value: -3, description: '灵魂 -3' },
          { type: 'modify_hp', target: 'hp', value: -30, description: 'HP -30（魔力反噬）' },
          { type: 'set_flag', target: 'dark_mage', value: 1, description: '暗黑法师（失控）' },
          { type: 'set_flag', target: 'soul_corrupted', value: 1, description: '灵魂被侵蚀' },
        ],
        successText: '你在黑暗中找到了光明——禁忌知识的本质不过是更深的真理。你掌控了它，而非被它吞噬',
        failureText: '暗紫色的能量吞噬了你的意识...当你清醒过来时，你已不再是从前的自己',
      },
      {
        id: 'resist_temptation',
        title: '封回禁书',
        description: '你颤抖着合上了书本，把它放回原处。有些力量...不值得付出灵魂的代价',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
          { type: 'set_flag', target: 'resist_dark', value: 1, description: '抵抗诱惑' },
        ],
      },
      {
        id: 'report_book',
        title: '上报学院',
        description: '你把这件事告诉了院长。院长看着你，眼中闪过复杂的神色',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'set_flag', target: 'trusted_by_dean', value: 1, description: '院长信任' },
        ],
      },
    ],
    tag: 'dark',
    priority: 'critical',
  },
  {
    id: 'soul_corruption_consequence',
    title: '灵魂的裂痕',
    description: '自从那天起，你总在半夜惊醒——黑暗中有什么东西在啃食你的意识。镜子里，你的眼中偶尔闪过紫色的光芒。灵魂的侵蚀已经开始，你无法再假装什么都没发生。',
    minAge: 20,
    maxAge: 60,
    weight: 8,
    include: 'has.flag.soul_corrupted',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'seek_purification',
        title: '寻求净化',
        description: '你踏上朝圣之路，寻找传说中的圣泉',
        riskCheck: {
          attribute: 'spr',
          difficulty: 14,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 3, description: '灵魂 +3（净化成功）' },
          { type: 'modify_hp', target: 'hp', value: -10, description: 'HP -10（净化的代价）' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'spr', value: -2, description: '灵魂 -2（净化失败，反噬）' },
          { type: 'modify_hp', target: 'hp', value: -25, description: 'HP -25（净化失败）' },
          { type: 'set_flag', target: 'soul_corrupted', value: 1, description: '侵蚀加重' },
        ],
        successText: '圣泉的光芒洗涤了你的灵魂，黑暗被暂时压制。你感到前所未有的平静',
        failureText: '圣泉干涸了...黑暗在你体内嘲笑着你的无力。侵蚀比想象中更深层',
      },
      {
        id: 'embrace_darkness',
        title: '沉沦黑暗',
        description: '既然已经回不去了，不如彻底拥抱这份力量',
        effects: [
          { type: 'modify_attribute', target: 'mag', value: 4, description: '魔力 +4（黑暗增幅）' },
          { type: 'modify_attribute', target: 'spr', value: -4, description: '灵魂 -4' },
          { type: 'modify_hp', target: 'hp', value: -15, description: 'HP -15（身体被侵蚀）' },
          { type: 'set_flag', target: 'dark_embraced', value: 1, description: '彻底堕落' },
        ],
      },
      {
        id: 'inner_struggle',
        title: '内心挣扎',
        description: '你决定与心中的黑暗抗争到底',
        riskCheck: {
          attribute: 'spr',
          difficulty: 10,
          scale: 4,
        },
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2（抗争胜利）' },
          { type: 'modify_attribute', target: 'mag', value: 1, description: '魔力 +1' },
          { type: 'modify_hp', target: 'hp', value: -5, description: 'HP -5' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'spr', value: -2, description: '灵魂 -2' },
          { type: 'modify_hp', target: 'hp', value: -20, description: 'HP -20' },
          { type: 'set_flag', target: 'soul_corrupted', value: 1, description: '侵蚀持续' },
        ],
        successText: '你在黑暗中找到了一丝光明——虽然伤痕累累，但你的意志更加坚定了',
        failureText: '黑暗太深了...你感到自己的灵魂在被一点点吞噬',
      },
    ],
    tag: 'dark',
    priority: 'major',
  },
  {
    id: 'tavern_brawl',
    title: '酒馆斗殴',
    description: '几杯麦酒下肚，一个兽人对你的长相发表了不当评论。',
    minAge: 18,
    maxAge: 25,
    weight: 6,
    include: 'attribute.str >= 6',
    effects: [
      { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
      { type: 'modify_hp', target: 'hp', value: -20, description: 'HP -20' },
      { type: 'set_flag', target: 'tough_reputation', value: 1, description: '硬汉名声' },
    ],
    unique: true,
    tag: 'combat',
    priority: 'minor',
  },
  {
    id: 'fairy_friend_return',
    title: '精灵的报恩',
    description: '当年你救下的精灵回来了，它带来了一颗星光果实。',
    minAge: 18,
    maxAge: 25,
    weight: 2,
    include: 'has.flag.fairy_friend',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
      { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
      { type: 'modify_hp', target: 'hp', value: 5, description: 'HP +5' },
    ],
    tag: 'adventure',
    priority: 'major',
  },
  {
    id: 'advanced_dungeon',
    title: '深渊地下城',
    description: '你听说了一座从未有人活着出来的地下城。在那里，冒险者公会悬赏的S级魔兽盘踞其中。你以前的经验告诉你——这次不一样。',
    minAge: 18,
    maxAge: 25,
    weight: 5,
    include: 'has.flag.dungeon_veteran',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'deep_dive',
        title: '深入深渊',
        description: '你点燃火把，一步步走入了黑暗深处',
        probability: 0.4,
        riskCheck: {
          attribute: 'str',
          difficulty: 16,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_attribute', target: 'mny', value: 4, description: '家境 +4' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
          { type: 'set_flag', target: 'dungeon_master', value: 1, description: '地下城征服者' },
        ],
        failureEffects: [
          { type: 'modify_hp', target: 'hp', value: -40, description: 'HP -40（险些丧命）' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1（绝境求生）' },
        ],
        successText: '你击败了S级魔兽！在它的巢穴中，你发现了古代文明的遗产',
        failureText: '你拼死逃了出来...这一次，你离死亡只有一步之遥',
      },
      {
        id: 'cautious_explore',
        title: '谨慎推进',
        description: '你利用以往的经验，步步为营地探索',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
        ],
      },
      {
        id: 'team_up',
        title: '组队挑战',
        description: '你在公会里找到了几个志同道合的冒险者组队',
        probability: 0.2,
        requireCondition: 'attribute.chr >= 10',
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'mny', value: 3, description: '家境 +3' },
          { type: 'set_flag', target: 'team_leader', value: 1, description: '团队领袖' },
        ],
      },
    ],
    tag: 'adventure',
    priority: 'critical',
  },
  {
    id: 'merchant_career',
    title: '商路崛起',
    description: '你的生意越做越大，开始涉足跨城贸易。路上的商队、海盗、税收官——每一个都是考验。',
    minAge: 22,
    maxAge: 30,
    weight: 5,
    include: 'has.flag.merchant_apprentice',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'expand_business',
        title: '扩张商路',
        description: '你投入了大量资金开辟新商路，这是一场豪赌',
        probability: 0.5,
        riskCheck: {
          attribute: 'int',
          difficulty: 14,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 5, description: '家境 +5' },
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2' },
          { type: 'set_flag', target: 'merchant_master', value: 1, description: '商业大亨' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'mny', value: -2, description: '家境 -2（亏损）' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（花钱买教训）' },
        ],
        successText: '你的商队遍布王国！各地的商人都知道你的名字',
        failureText: '货物被海盗截了...你血本无归，但至少保住了命',
      },
      {
        id: 'steady_trade',
        title: '稳扎稳打',
        description: '你选择稳妥的本地贸易路线，虽然赚得慢但风险小',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
        ],
      },
    ],
    tag: 'social',
    priority: 'critical',
  },
  {
    id: 'heartbreak_growth',
    title: '失恋之后',
    description: '那之后的日子里，你反复想着那个人说过的话、做过的事。痛苦渐渐化作了某种更深的东西。',
    minAge: 15,
    maxAge: 18,
    weight: 6,
    include: 'has.flag.heartbroken',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'meditate_growth',
        title: '沉淀修炼',
        description: '你把所有精力都投入到了修炼中，用汗水洗去悲伤',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'set_flag', target: 'heartbreak_growth', value: 1, description: '在痛苦中成长' },
        ],
      },
      {
        id: 'become_cynical',
        title: '变得愤世嫉俗',
        description: '"这个世界根本不值得认真。"你冷笑着，把自己封闭起来',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（独特的冷漠气质）' },
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
          { type: 'set_flag', target: 'cynical', value: 1, description: '愤世嫉俗' },
        ],
      },
      {
        id: 'move_on',
        title: '释然放手',
        description: '你对着镜子笑了笑："好了，该向前看了。"',
        probability: 0.2,
        requireCondition: 'attribute.spr >= 6',
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
          { type: 'set_flag', target: 'emotional_maturity', value: 1, description: '情感成熟' },
        ],
      },
    ],
    tag: 'romance',
    priority: 'critical',
  },
  {
    id: 'knight_glory',
    title: '骑士的荣光',
    description: '你的骑士团接到了剿灭盗贼团的任务。作为正式骑士，你将第一次带领小队出征。',
    minAge: 18,
    maxAge: 25,
    weight: 5,
    include: 'has.flag.knight',
    unique: true,
    effects: [],
    branches: [
      {
        id: 'lead_charge',
        title: '带头冲锋',
        description: '"跟我上！"你拔出佩剑，第一个冲向敌阵',
        probability: 0.5,
        riskCheck: {
          attribute: 'str',
          difficulty: 16,
          scale: 3,
        },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2' },
          { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2' },
          { type: 'set_flag', target: 'knight_hero', value: 1, description: '骑士英雄' },
        ],
        failureEffects: [
          { type: 'modify_hp', target: 'hp', value: -30, description: 'HP -30' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
        ],
        successText: '你一马当先，势不可挡！盗贼团闻风丧胆，你赢得了骑士团的最高赞誉',
        failureText: '你受伤了，但你的勇气鼓舞了队友，最终取得了胜利',
      },
      {
        id: 'tactical_approach',
        title: '智取敌营',
        description: '你选择了夜袭——利用地形和夜色打他们一个措手不及',
        probability: 0.3,
        requireCondition: 'attribute.int >= 12',
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2' },
          { type: 'set_flag', target: 'knight_tactician', value: 1, description: '智将骑士' },
        ],
      },
      {
        id: 'protect_civilians',
        title: '保护平民',
        description: '你发现盗贼团扣押了村民，你决定先救人',
        probability: 0.2,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'set_flag', target: 'knight_honor', value: 1, description: '荣誉骑士' },
        ],
      },
    ],
    tag: 'combat',
    priority: 'critical',
  },

  // ==================== 中年期（31-60 岁） ====================
  {
    id: 'become_lord',
    title: '受封领主',
    description: '因为你的功绩，国王封你为一方领主。',
    minAge: 35,
    maxAge: 50,
    weight: 3,
    include: 'attribute.mny >= 10 & attribute.chr >= 8',
    effects: [
      { type: 'modify_attribute', target: 'mny', value: 3, description: '家境 +3' },
      { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
      { type: 'set_flag', target: 'lord', value: 1, description: '受封领主' },
    ],
    unique: true,
    tag: 'social',
    priority: 'major',
  },
  {
    id: 'master_spell',
    title: '顿悟！魔法真谛',
    description: '你终于理解了魔法的本质——不是操控元素，而是与世界的对话。',
    minAge: 40,
    maxAge: 55,
    weight: 3,
    include: 'attribute.mag >= 18 & attribute.int >= 14',
    effects: [
      { type: 'modify_attribute', target: 'mag', value: 3, description: '魔力 +3' },
      { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2' },
      { type: 'set_flag', target: 'archmage', value: 1, description: '大魔导师！' },
    ],
    unique: true,
    tag: 'magic',
    priority: 'major',
  },
  {
    id: 'student_successor',
    title: '收徒传艺',
    description: '一个年轻人跪在你面前："请收我为徒！"',
    minAge: 35,
    maxAge: 55,
    weight: 8,
    include: 'attribute.str >= 14 | attribute.mag >= 14',
    exclude: 'has.flag.has_student',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
      { type: 'set_flag', target: 'has_student', value: 1, description: '收了徒弟' },
    ],
    tag: 'social',
    priority: 'major',
  },
  {
    id: 'lost_in_dungeon',
    title: '地下城迷失',
    description: '你在深层的地下城中迷路了，黑暗中有什么在注视着你。',
    minAge: 35,
    maxAge: 50,
    weight: 5,
    effects: [
      { type: 'modify_hp', target: 'hp', value: -30, description: 'HP -30', probability: 0.5 },
      { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1', probability: 0.5 },
      { type: 'modify_hp', target: 'hp', value: 8, description: 'HP +8（找到宝藏！）', probability: 0.5 },
      { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1', probability: 0.5 },
      { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1', probability: 0.5 },
    ],
    unique: true,
    tag: 'adventure',
    priority: 'minor',
  },
  {
    id: 'war_breaks_out',
    title: '战争爆发',
    description: '魔王军入侵了！所有冒险者被征召。',
    minAge: 40,
    maxAge: 55,
    weight: 5,
    effects: [],
    branches: [
      {
        id: 'war_frontline',
        title: '上前线',
        description: '你冲在最前面',
        requireCondition: 'attribute.str >= 10',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_hp', target: 'hp', value: -40, description: 'HP -40' },
          { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2' },
          { type: 'set_flag', target: 'war_veteran', value: 1, description: '战争老兵' },
        ],
      },
      {
        id: 'war_support',
        title: '后方支援',
        description: '你在后方提供支援',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'set_flag', target: 'healer', value: 1, description: '治愈者' },
        ],
      },
      {
        id: 'war_hero',
        title: '带队突击',
        description: '你带领精锐小队直取敌军主将！',
        requireCondition: 'attribute.chr >= 15 & attribute.str >= 14',
        probability: 0.2,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2' },
          { type: 'modify_hp', target: 'hp', value: -50, description: 'HP -50' },
          { type: 'modify_attribute', target: 'mny', value: 3, description: '家境 +3' },
          { type: 'set_flag', target: 'war_hero', value: 1, description: '战争英雄！' },
        ],
      },
    ],
    unique: true,
    tag: 'epic',
    priority: 'critical',
  },
  {
    id: 'world_breaking_start',
    title: '世界崩坏开始',
    description: '你感到世界在颤抖。不是地震——是世界本身的法则在瓦解。',
    minAge: 50,
    maxAge: 60,
    weight: 1,
    include: 'has.talent.worldbreaker',
    effects: [
      { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
      { type: 'modify_attribute', target: 'mag', value: 3, description: '魔力 +3' },
      { type: 'set_flag', target: 'world_breaking', value: 1, description: '世界崩坏开始' },
    ],
    unique: true,
    tag: 'epic',
    priority: 'major',
  },
  {
    id: 'midlife_crisis',
    title: '中年危机',
    description: '"我这辈子到底在干什么？"你站在悬崖边，看着夕阳发呆。',
    minAge: 40,
    maxAge: 50,
    weight: 10,
    unique: true,
    effects: [],
    branches: [
      {
        id: 'let_go',
        title: '放下执念',
        description: '你深吸一口气，决定放下过去的遗憾',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
          { type: 'modify_hp', target: 'hp', value: 5, description: 'HP +5' },
          { type: 'set_flag', target: 'inner_peace', value: 1, description: '内心平静' },
        ],
      },
      {
        id: 'persist_dream',
        title: '坚持梦想',
        description: '"还没完！"你攥紧拳头，重新燃起了斗志',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'set_flag', target: 'never_give_up', value: 1, description: '永不放弃' },
        ],
      },
    ],
    tag: 'life',
    priority: 'critical',
  },
  {
    id: 'reincarnated_invention',
    title: '前世知识变现',
    description: '你想起前世的配方，调出了一种这个世界从未见过的药剂——可乐。一夜之间风靡王国。',
    minAge: 30,
    maxAge: 40,
    weight: 1,
    include: 'attribute.int >= 10',
    effects: [
      { type: 'modify_attribute', target: 'mny', value: 5, description: '家境 +5' },
      { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
      { type: 'set_flag', target: 'famous_inventor', value: 1, description: '可乐发明者！' },
    ],
    unique: true,
    tag: 'epic',
    priority: 'major',
  },

  // ==================== 老年期（61-80 岁） ====================
  {
    id: 'retirement',
    title: '挂剑归隐',
    description: '你把武器挂在了壁炉上方，决定安度晚年。',
    minAge: 60,
    maxAge: 70,
    weight: 10,
    unique: true,
    effects: [],
    branches: [
      {
        id: 'retire_peaceful',
        title: '归隐山林',
        description: '你买了一座小木屋，在山林间过起了悠闲的日子',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 3, description: '灵魂 +3' },
          { type: 'modify_hp', target: 'hp', value: 8, description: 'HP +8' },
          { type: 'set_flag', target: 'peaceful_retirement', value: 1, description: '安享晚年' },
        ],
      },
      {
        id: 'continue_adventure',
        title: '继续冒险',
        description: '"老夫还没老到走不动路！"你擦亮了剑',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_hp', target: 'hp', value: -20, description: 'HP -20' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'set_flag', target: 'never_retired', value: 1, description: '永不退休' },
        ],
      },
    ],
    tag: 'life',
    priority: 'critical',
  },
  {
    id: 'legend_spread',
    title: '传说的传播',
    description: '吟游诗人们开始传唱你的故事。',
    minAge: 65,
    maxAge: 75,
    weight: 8,
    include: 'attribute.chr >= 15',
    effects: [
      { type: 'modify_attribute', target: 'chr', value: 3, description: '魅力 +3' },
      { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
    ],
    unique: true,
    tag: 'social',
    priority: 'major',
  },
  {
    id: 'final_cataclysm',
    title: '终焉之战',
    description: '天空裂开，混沌涌入。世界需要一个终章。而你，就是执笔之人。',
    minAge: 55,
    maxAge: 65,
    weight: 1,
    include: 'has.talent.worldbreaker',
    effects: [],
    branches: [
      {
        id: 'destroy_world',
        title: '毁灭世界',
        description: '你选择终结一切',
        requireCondition: 'attribute.str >= 22 | attribute.mag >= 26',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: -5, description: '灵魂 -5' },
          { type: 'modify_attribute', target: 'str', value: 3, description: '体魄 +3' },
          { type: 'modify_attribute', target: 'mag', value: 3, description: '魔力 +3' },
          { type: 'set_flag', target: 'world_destroyed', value: 1, description: '世界毁灭者' },
        ],
      },
      {
        id: 'rebuild_world',
        title: '重建世界',
        description: '你选择重塑一切',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 5, description: '灵魂 +5' },
          { type: 'modify_attribute', target: 'int', value: 3, description: '智慧 +3' },
          { type: 'set_flag', target: 'world_rebuilt', value: 1, description: '世界重建者' },
        ],
      },
      {
        id: 'become_god',
        title: '成为新世界的神',
        description: '你超越了凡人的界限',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2' },
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2' },
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2' },
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2' },
          { type: 'modify_attribute', target: 'mag', value: 2, description: '魔力 +2' },
          { type: 'modify_attribute', target: 'luk', value: 2, description: '运势 +2' },
          { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2' },
          { type: 'set_flag', target: 'became_god', value: 1, description: '新世界的神！' },
        ],
      },
    ],
    unique: true,
    tag: 'epic',
    priority: 'critical',
  },
  {
    id: 'peaceful_end',
    title: '平静的终章',
    description: '你坐在门廊的摇椅上，看着孙辈们在花园里奔跑。夕阳很美。',
    minAge: 70,
    maxAge: 80,
    weight: 12,
    include: 'attribute.spr >= 8',
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'spr', value: 3, description: '灵魂 +3' },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'magic_breakthrough_final',
    title: '最后的魔法',
    description: '你感到自己的魔力在消散，于是决定将毕生所学注入最后一道法术。',
    minAge: 70,
    maxAge: 80,
    weight: 4,
    include: 'attribute.mag >= 22',
    effects: [
      { type: 'modify_attribute', target: 'mag', value: 5, description: '魔力 +5（最后一刻的辉煌）' },
      { type: 'modify_hp', target: 'hp', value: -30, description: 'HP -30' },
    ],
    unique: true,
    tag: 'magic',
    priority: 'major',
  },

  // ==================== 填充事件 v2 - 打破固定链条 ====================

  {
    id: 'childhood_play',
    title: '村口的泥巴大战',
    description: '你和邻居家的小孩在村口展开了一场激烈的泥巴大战！',
    minAge: 3,
    maxAge: 6,
    weight: 5,
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（开心）' },
    ],
    tag: 'childhood',
    priority: 'minor',
  },
  {
    id: 'steal_sweets',
    effects: [],
    title: '偷吃糖果',
    description: '你趁妈妈不注意偷拿了一颗糖果，结果被发现了。',
    minAge: 3,
    maxAge: 7,
    weight: 4,
    unique: true,
    branches: [
      {
        id: 'apologize',
        title: '老实道歉',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
        ],
      },
      {
        id: 'lie_about_it',
        title: '撒谎',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1' },
        ],
      },
      {
        id: 'blame_sibling',
        title: '嫁祸给兄弟/姐妹',
        probability: 0.2,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'modify_attribute', target: 'chr', value: -1, description: '魅力 -1' },
        ],
      },
    ],
    tag: 'childhood',
    priority: 'minor',
  },
  {
    id: 'first_snow',
    title: '初雪',
    description: '今年第一场雪，你兴奋地冲出门堆雪人。',
    minAge: 3,
    maxAge: 8,
    weight: 4,
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
    ],
    tag: 'childhood',
    priority: 'minor',
  },
  {
    id: 'tree_climbing',
    title: '爬树冒险',
    description: '你挑战爬上了村里最高的那棵树。',
    minAge: 5,
    maxAge: 10,
    weight: 4,
    unique: true,
    riskCheck: { attribute: 'str', difficulty: 5, scale: 2 },
    effects: [
      { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（成就感）' },
    ],
    failureEffects: [
      { type: 'modify_hp', target: 'hp', value: -8, description: 'HP -8（摔下来了）' },
    ],
    successText: '你站在树顶，俯瞰整个村庄！',
    failureText: '你从树上掉了下来...还好是草地。',
    tag: 'childhood',
    priority: 'minor',
  },
  {
    id: 'river_fishing',
    effects: [],
    title: '河边抓鱼',
    description: '你和朋友们去河边抓鱼，这是孩子们最喜欢的消遣。',
    minAge: 6,
    maxAge: 12,
    weight: 5,
    unique: true,
    branches: [
      {
        id: 'patient_fish',
        title: '耐心等待',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
          { type: 'modify_attribute', target: 'mny', value: 1, description: '家境 +1（卖了鱼）' },
        ],
      },
      {
        id: 'chase_fish',
        title: '直接下水',
        probability: 0.4,
        riskCheck: { attribute: 'str', difficulty: 5, scale: 2 },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
        ],
        failureEffects: [
          { type: 'modify_hp', target: 'hp', value: -5, description: 'HP -5（被水冲走）' },
        ],
      },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'explore_ruins',
    effects: [],
    title: '废墟探险',
    description: '村子外面的森林深处有一座废弃的小屋，传说里面闹鬼。',
    minAge: 8,
    maxAge: 13,
    weight: 4,
    unique: true,
    branches: [
      {
        id: 'enter_ruins',
        title: '推门进去',
        probability: 0.5,
        riskCheck: { attribute: 'spr', difficulty: 6, scale: 3 },
        effects: [
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2（发现了古老地图）' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（勇气）' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1（被吓到了）' },
          { type: 'modify_hp', target: 'hp', value: -5, description: 'HP -5（被蝙蝠咬了）' },
        ],
        successText: '你发现了一本泛黄的古书和一张画满符号的地图！',
        failureText: '一只蝙蝠突然飞到你脸上！你落荒而逃...',
      },
      {
        id: 'peek_from_outside',
        title: '在外面偷看',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
        ],
      },
      {
        id: 'run_away',
        title: '不敢靠近',
        probability: 0.2,
        effects: [],
      },
    ],
    tag: 'adventure',
    priority: 'minor',
  },
  {
    id: 'help_farmer',
    title: '帮农夫收麦',
    description: '村里老农夫身体不好，你主动去帮他干活。',
    minAge: 10,
    maxAge: 15,
    weight: 5,
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
      { type: 'modify_attribute', target: 'mny', value: 1, description: '家境 +1（得到报酬）' },
      { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（村民好感）' },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'wander_market',
    effects: [],
    title: '逛集市',
    description: '每个月一次的集市来了！你口袋里有一点零花钱。',
    minAge: 8,
    maxAge: 15,
    weight: 5,
    unique: true,
    branches: [
      {
        id: 'buy_book',
        title: '买了一本旧书',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
        ],
      },
      {
        id: 'buy_snack',
        title: '买零食吃',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
        ],
      },
      {
        id: 'save_money',
        title: '存起来',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 1, description: '家境 +1' },
        ],
      },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'star_gazing',
    title: '观星',
    description: '夏夜，你躺在草地上仰望星空，想着自己为什么会来到这个世界。',
    minAge: 10,
    maxAge: 20,
    weight: 3,
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
      { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'street_performance',
    effects: [],
    title: '街头表演',
    description: '你看到有人在集市上表演杂技，围观的人都在鼓掌。',
    minAge: 12,
    maxAge: 18,
    weight: 3,
    unique: true,
    branches: [
      {
        id: 'try_perform',
        title: '上台尝试',
        probability: 0.4,
        riskCheck: { attribute: 'chr', difficulty: 8, scale: 3 },
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2' },
          { type: 'modify_attribute', target: 'mny', value: 1, description: '家境 +1（打赏）' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'chr', value: -1, description: '魅力 -1（出丑了）' },
        ],
        successText: '你的表演让全场沸腾！',
        failureText: '你摔了个狗吃屎...尴尬。',
      },
      {
        id: 'just_watch',
        title: '继续看',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（学到了）' },
        ],
      },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'part_time_work',
    title: '打零工',
    description: '你决定在镇上的铁匠铺帮忙赚点零花钱。',
    minAge: 14,
    maxAge: 18,
    weight: 4,
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
      { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2' },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'meteor_shower',
    title: '流星雨',
    description: '今晚有流星雨，整个村庄的人都出来了。',
    minAge: 15,
    maxAge: 25,
    weight: 2,
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'traveling_merchant',
    effects: [],
    title: '旅行商人',
    description: '一个来自远方的商人来到村里，带来了各种新奇的商品和故事。',
    minAge: 15,
    maxAge: 25,
    weight: 3,
    unique: true,
    branches: [
      {
        id: 'listen_stories',
        title: '听他讲故事',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
        ],
      },
      {
        id: 'buy_something',
        title: '买了一件奇怪的东西',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1' },
        ],
      },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'forest_camping',
    effects: [],
    title: '森林露营',
    description: '你和朋友们决定在森林里露营一晚。',
    minAge: 16,
    maxAge: 22,
    weight: 3,
    unique: true,
    branches: [
      {
        id: 'enjoy_night',
        title: '享受星空',
        probability: 0.5,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
        ],
      },
      {
        id: 'explore_night',
        title: '夜间探险',
        probability: 0.3,
        riskCheck: { attribute: 'str', difficulty: 8, scale: 2 },
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（勇气）' },
        ],
        failureEffects: [
          { type: 'modify_hp', target: 'hp', value: -5, description: 'HP -5（被荆棘划伤）' },
        ],
      },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'scenic_travel',
    title: '远行见世面',
    description: '你攒够了钱，决定去邻城看看。',
    minAge: 25,
    maxAge: 40,
    weight: 3,
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
      { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'teaching_others',
    title: '传授经验',
    description: '一些年轻人来向你请教经验，你很乐意分享。',
    minAge: 35,
    maxAge: 55,
    weight: 3,
    unique: true,
    effects: [
      { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1' },
      { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'childhood_chase',
    title: '抓蜻蜓',
    description: '夏日午后，你拿着自制的小网兜在草丛间追逐蜻蜓。',
    minAge: 3,
    maxAge: 6,
    weight: 5,
    unique: true,
    effects: [],
    branches: [
      {
        id: 'catch_one',
        title: '抓到了一只',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（开心）' },
        ],
      },
      {
        id: 'fall_down',
        title: '摔了一跤',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1（皮实了）' },
        ],
      },
      {
        id: 'let_go',
        title: '抓到又放了',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（善良）' },
        ],
      },
    ],
    tag: 'childhood',
    priority: 'minor',
  },
  {
    id: 'childhood_hide_seek',
    title: '捉迷藏',
    description: '你和小伙伴们玩起了捉迷藏，你来当躲藏的那一个。',
    minAge: 3,
    maxAge: 6,
    weight: 5,
    unique: true,
    effects: [],
    branches: [
      {
        id: 'hide_well',
        title: '藏得太好没人找到',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（善于观察）' },
        ],
      },
      {
        id: 'found_quickly',
        title: '很快被找到了',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（和大家一起笑）' },
        ],
      },
      {
        id: 'hide_scary_place',
        title: '躲进了 scary 的地方',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1（吓哭了）' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1（胆量锻炼）' },
        ],
      },
    ],
    tag: 'childhood',
    priority: 'minor',
  },
  {
    id: 'childhood_pet',
    title: '捡到受伤小鸟',
    description: '你在草丛里发现了一只翅膀受伤的小鸟，它正可怜地叫着。',
    minAge: 3,
    maxAge: 6,
    weight: 5,
    unique: true,
    effects: [],
    branches: [
      {
        id: 'heal_bird',
        title: '带回家照顾',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（温柔）' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
        ],
      },
      {
        id: 'leave_bird',
        title: '看了一眼就走了',
        probability: 0.3,
        effects: [],
      },
      {
        id: 'call_adult',
        title: '去找大人帮忙',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（懂得求助）' },
        ],
      },
    ],
    tag: 'childhood',
    priority: 'minor',
  },
  {
    id: 'village_race',
    effects: [],
    title: '村里赛跑',
    description: '村里举办了一年一度的赛跑比赛，你决定报名参加。',
    minAge: 10,
    maxAge: 14,
    weight: 5,
    unique: true,
    branches: [
      {
        id: 'sprint_hard',
        title: '全力冲刺',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（跑完很爽）' },
        ],
      },
      {
        id: 'pacing_strategy',
        title: '合理分配体力',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（懂得策略）' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
        ],
      },
      {
        id: 'trip_over',
        title: '途中绊倒了',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1（摔出来的韧性）' },
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1（丢脸）' },
        ],
      },
    ],
    tag: 'childhood',
    priority: 'minor',
  },
  {
    id: 'old_soldier_story',
    effects: [],
    title: '老兵的故事',
    description: '村口的老兵又坐在树下，几个孩子围着他，听他讲年轻时的战场经历。',
    minAge: 10,
    maxAge: 14,
    weight: 5,
    unique: true,
    branches: [
      {
        id: 'listen_carefully',
        title: '认真听完',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（学到经验）' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1（被激励了）' },
        ],
      },
      {
        id: 'ask_questions',
        title: '追问他战斗的细节',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2（深入了解）' },
        ],
      },
      {
        id: 'bored_leave',
        title: '觉得无聊走开了',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（去玩了）' },
        ],
      },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'catch_thief',
    effects: [],
    title: '抓小偷',
    description: '集市上有人大喊"抓小偷！"，一个黑影从你身边窜过。',
    minAge: 10,
    maxAge: 14,
    weight: 5,
    unique: true,
    branches: [
      {
        id: 'chase_thief',
        title: '追上去',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（见义勇为）' },
        ],
      },
      {
        id: 'block_path',
        title: '拦住去路',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（机智）' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
        ],
      },
      {
        id: 'shout_alert',
        title: '大声喊叫提醒别人',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（正义感）' },
        ],
      },
    ],
    tag: 'adventure',
    priority: 'minor',
  },
  {
    id: 'old_friend_reunion',
    effects: [],
    title: '老友重逢',
    description: '在城里的酒馆，你遇到了多年未见的老朋友。你们曾经一起在泥巴地里打滚，如今他已是一方小有名气的商人。',
    minAge: 35,
    maxAge: 45,
    weight: 4,
    unique: true,
    branches: [
      {
        id: 'drink_together',
        title: '坐下来喝一杯',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（叙旧很愉快）' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（人脉）' },
        ],
      },
      {
        id: 'business_proposal',
        title: '聊起了合作生意',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 1, description: '家境 +1（商机）' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（商业头脑）' },
        ],
      },
      {
        id: 'polite_decline',
        title: '寒暄几句后告别',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（释然）' },
        ],
      },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'apprentice_contest',
    effects: [],
    title: '弟子比武大会',
    description: '城中举办了一年一度的弟子比武大会，各门各派的年轻弟子齐聚一堂，切磋武艺。',
    minAge: 35,
    maxAge: 45,
    weight: 4,
    unique: true,
    branches: [
      {
        id: 'coach_disciple',
        title: '指导自己的弟子参赛',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（师者风范）' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（教学相长）' },
        ],
      },
      {
        id: 'watch_and_bet',
        title: '在场边观战押注',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1（运气不错）' },
          { type: 'modify_attribute', target: 'mny', value: 1, description: '家境 +1（赢了一笔）' },
        ],
      },
      {
        id: 'join_exhibition',
        title: '上台表演助兴',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1（活动筋骨）' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（赢得喝彩）' },
        ],
      },
    ],
    tag: 'life',
    priority: 'minor',
  },
  {
    id: 'village_festival',
    effects: [],
    title: '村里祭典',
    description: '丰收的季节到了，村子里举办了一年一度的祭典，到处都是热闹的摊位和欢笑声。',
    minAge: 3,
    maxAge: 6,
    weight: 5,
    unique: true,
    branches: [
      {
        id: 'festival_eat',
        title: '大吃特吃',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（满足）' },
        ],
      },
      {
        id: 'festival_dance',
        title: '跟着大人们跳舞',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（开心）' },
        ],
      },
      {
        id: 'festival_watch_fireworks',
        title: '等烟花',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 2, description: '灵魂 +2（美好回忆）' },
        ],
      },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'stray_dog',
    effects: [],
    title: '流浪狗',
    description: '你在回家的路上遇到了一只脏兮兮的流浪小狗，它用湿漉漉的眼睛看着你。',
    minAge: 4,
    maxAge: 7,
    weight: 5,
    unique: true,
    branches: [
      {
        id: 'adopt_dog',
        title: '带它回家',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（有了伙伴）' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1' },
        ],
      },
      {
        id: 'share_food',
        title: '分给它一半馒头',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（善良）' },
        ],
      },
      {
        id: 'ignore_dog',
        title: '害怕地跑开',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1（心里不安）' },
        ],
      },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'bounty_notice',
    effects: [],
    title: '悬赏告示板',
    description: '镇上告示板贴满了冒险委托，你最感兴趣的是一个奇怪的委托...',
    minAge: 16,
    maxAge: 22,
    weight: 3,
    unique: true,
    branches: [
      {
        id: 'accept_strange_quest',
        title: '接下奇怪委托',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'luk', value: 2, description: '运势 +2（奇遇开端）' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（冒险之心）' },
        ],
      },
      {
        id: 'take_normal_quest',
        title: '只接普通委托',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2（报酬）' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1（锻炼）' },
        ],
      },
      {
        id: 'help_friend_quest',
        title: '帮朋友接委托',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2（友谊加深）' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（助人为乐）' },
        ],
      },
    ],
    tag: 'adventure',
    priority: 'major',
  },
  {
    id: 'love_at_first_sight',
    effects: [],
    title: '一见钟情',
    description: '在集市上你看到了一个人，心跳突然加速...',
    minAge: 16,
    maxAge: 22,
    weight: 5,
    unique: true,
    branches: [
      {
        id: 'approach_them',
        title: '上前搭讪',
        probability: 0.35,
        riskCheck: { attribute: 'chr', difficulty: 10, scale: 3 },
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2（勇气可嘉）' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（心动）' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1（尴尬）' },
        ],
        successText: '你们聊得很投机，交换了名字。',
        failureText: '你紧张得说不出话，红着脸跑开了...',
      },
      {
        id: 'watch_from_afar',
        title: '远远偷看',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（暗恋的滋味）' },
        ],
      },
      {
        id: 'pretend_not_care',
        title: '装作不在意',
        probability: 0.3,
        effects: [],
      },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'secret_training',
    effects: [],
    title: '秘密特训',
    description: '你发现了一个隐秘的训练场，里面只有你一个人...',
    minAge: 15,
    maxAge: 21,
    weight: 3,
    unique: true,
    branches: [
      {
        id: 'train_hard',
        title: '独自苦练',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（悟出心得）' },
        ],
      },
      {
        id: 'explore_depths',
        title: '探索深处',
        probability: 0.35,
        riskCheck: { attribute: 'str', difficulty: 8, scale: 2 },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（发现秘密）' },
        ],
        failureEffects: [
          { type: 'modify_hp', target: 'hp', value: -10, description: 'HP -10（掉进陷阱）' },
        ],
        successText: '你在深处发现了一个古老的修炼痕迹，受益匪浅！',
        failureText: '你不小心触发了隐藏的机关，受了点伤。',
      },
      {
        id: 'leave_training',
        title: '离开',
        probability: 0.25,
        effects: [],
      },
    ],
    tag: 'adventure',
    priority: 'major',
  },
  {
    id: 'investment_opportunity',
    effects: [],
    title: '投资机会',
    description: '一个商人向你推荐了一个"稳赚不赔"的投资项目，承诺三个月内翻倍回报。',
    minAge: 25,
    maxAge: 40,
    weight: 4,
    unique: true,
    branches: [
      {
        id: 'invest_all',
        title: '全部投入',
        probability: 0.35,
        riskCheck: { attribute: 'luk', difficulty: 12, scale: 3 },
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 5, description: '家境 +5（投资大赚）' },
        ],
        failureEffects: [
          { type: 'modify_attribute', target: 'mny', value: -8, description: '家境 -8（血本无归）' },
        ],
        successText: '三个月后商人如约而至，你赚得盆满钵满！',
        failureText: '商人卷款跑路了，你的积蓄化为乌有...',
      },
      {
        id: 'invest_half',
        title: '投入一半',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'mny', value: 2, description: '家境 +2（小有收益）' },
        ],
      },
      {
        id: 'reject_invest',
        title: '拒绝',
        probability: 0.3,
        effects: [],
      },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'mysterious_stranger',
    effects: [],
    title: '神秘旅人',
    description: '在旅途中你遇到了一个戴面具的旅人，他似乎知道你的过去...',
    minAge: 25,
    maxAge: 35,
    weight: 4,
    unique: true,
    branches: [
      {
        id: 'talk_to_stranger',
        title: '和他交谈',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2（获得了隐秘知识）' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（命运交织）' },
          { type: 'set_flag', target: 'mysterious_encounter', value: true, description: '触发了神秘遭遇' },
        ],
      },
      {
        id: 'stay_alert',
        title: '警惕远离',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（直觉敏锐）' },
        ],
      },
      {
        id: 'treat_drink',
        title: '请他喝酒',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（豪爽）' },
          { type: 'modify_attribute', target: 'mny', value: -1, description: '家境 -1（请客花销）' },
        ],
      },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'old_rival',
    effects: [],
    title: '老对手来访',
    description: '多年未见的老对手突然来访，他看起来苍老了许多...',
    minAge: 40,
    maxAge: 60,
    weight: 4,
    unique: true,
    branches: [
      {
        id: 'warm_welcome',
        title: '热情招待',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2（以德报怨）' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（释怀）' },
        ],
      },
      {
        id: 'cold_shoulder',
        title: '冷眼相待',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（冷静判断）' },
        ],
      },
      {
        id: 'challenge_fight',
        title: '比试一场',
        probability: 0.3,
        riskCheck: { attribute: 'str', difficulty: 12, scale: 2 },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2（宝刀未老）' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（赢得尊重）' },
        ],
        failureEffects: [
          { type: 'modify_hp', target: 'hp', value: -15, description: 'HP -15（老伤复发）' },
        ],
        successText: '你赢了！老对手心服口服，两人相视大笑。',
        failureText: '你输了一招，旧伤隐隐作痛...',
      },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'legacy_question',
    effects: [],
    title: '传承之问',
    description: '一个年轻人来找你，想要继承你的技艺...',
    minAge: 50,
    maxAge: 65,
    weight: 4,
    unique: true,
    branches: [
      {
        id: 'teach_everything',
        title: '倾囊相授',
        probability: 0.4,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2（教学相长）' },
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2（受人敬仰）' },
          { type: 'set_flag', target: 'legacy_passed', value: true, description: '传承技艺' },
        ],
      },
      {
        id: 'think_about_it',
        title: '考虑一下',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（沉思）' },
        ],
      },
      {
        id: 'refuse_request',
        title: '拒绝',
        probability: 0.25,
        effects: [],
      },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'village_feud',
    effects: [],
    title: '村长之争',
    description: '两个家族因为土地边界争吵不休，你恰好目击了一切...',
    minAge: 7,
    maxAge: 12,
    weight: 4,
    unique: true,
    branches: [
      {
        id: 'speak_for_weak',
        title: '帮弱者说话',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2（正义之声）' },
          { type: 'set_flag', target: 'justice_lover', value: true, description: '成为正义之人' },
        ],
      },
      {
        id: 'pretend_not_see',
        title: '假装没看到',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: -1, description: '灵魂 -1（内心不安）' },
        ],
      },
      {
        id: 'tell_adult',
        title: '去告诉大人',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（懂得求助）' },
        ],
      },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'lost_treasure_map',
    effects: [],
    title: '藏宝图碎片',
    description: '你在河里洗脚时踩到了一块刻着奇怪符号的石头...',
    minAge: 8,
    maxAge: 14,
    weight: 4,
    unique: true,
    branches: [
      {
        id: 'study_carefully',
        title: '仔细研究',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2（解谜天赋）' },
          { type: 'set_flag', target: 'treasure_hunter', value: true, description: '成为寻宝者' },
        ],
      },
      {
        id: 'throw_away',
        title: '扔掉它',
        probability: 0.3,
        effects: [],
      },
      {
        id: 'hide_it',
        title: '藏起来',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'luk', value: 1, description: '运势 +1（直觉）' },
        ],
      },
    ],
    tag: 'adventure',
    priority: 'major',
  },
  {
    id: 'young_rival',
    effects: [],
    title: '少年的对手',
    description: '镇上来了一个和你同龄的天才少年，大家总是拿你们比较...',
    minAge: 9,
    maxAge: 14,
    weight: 4,
    unique: true,
    branches: [
      {
        id: 'surpass_him',
        title: '努力超越他',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1（刻苦锻炼）' },
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（勤学不辍）' },
        ],
      },
      {
        id: 'befriend_him',
        title: '和他交朋友',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: 2, description: '魅力 +2（赢得友谊）' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（惺惺相惜）' },
        ],
      },
      {
        id: 'ignore_him',
        title: '无视他',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（自在）' },
        ],
      },
    ],
    tag: 'life',
    priority: 'major',
  },
  {
    id: 'rainy_day_adventure',
    title: '雨日冒险',
    description: '下着大雨，你偷偷溜出家门，在雨中发现了一个被废弃的地窖入口...',
    minAge: 5,
    maxAge: 9,
    weight: 4,
    unique: true,
    effects: [],
    branches: [
      {
        id: 'enter_cellar',
        title: '钻进去看看',
        description: '你鼓起勇气，摸黑走进了地窖',
        probability: 0.4,
        riskCheck: {
          attribute: 'spr',
          difficulty: 6,
          scale: 2,
        },
        effects: [
          { type: 'modify_attribute', target: 'int', value: 2, description: '智慧 +2（地窖中的发现）' },
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（勇气试炼）' },
          { type: 'modify_hp', target: 'hp', value: -8, description: 'HP -8（跌落受伤）' },
        ],
      },
      {
        id: 'wait_at_door',
        title: '在门口等雨停',
        probability: 0.35,
        effects: [
          { type: 'modify_attribute', target: 'spr', value: 1, description: '灵魂 +1（静心聆听雨声）' },
        ],
      },
      {
        id: 'run_home_rain',
        title: '跑回家',
        probability: 0.25,
        effects: [],
      },
    ],
    tag: 'adventure',
    priority: 'major',
  },
  {
    id: 'first_competition',
    title: '第一次比赛',
    description: '村里举办了一年一度的儿童比赛，你被推上了赛场...',
    minAge: 6,
    maxAge: 10,
    weight: 4,
    unique: true,
    effects: [],
    branches: [
      {
        id: 'go_all_out',
        title: '拼尽全力',
        description: '你咬紧牙关，使出了全部力气',
        probability: 0.4,
        riskCheck: {
          attribute: 'str',
          difficulty: 6,
          scale: 2,
        },
        effects: [
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2（全力拼搏）' },
          { type: 'modify_attribute', target: 'chr', value: 1, description: '魅力 +1（赢得喝彩）' },
          { type: 'modify_attribute', target: 'str', value: 1, description: '体魄 +1（虽败犹荣）' },
        ],
      },
      {
        id: 'strategic_forfeit',
        title: '策略性放弃',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'int', value: 1, description: '智慧 +1（审时度势）' },
        ],
      },
      {
        id: 'dirty_trick',
        title: '暗中使绊',
        description: '你趁裁判不注意，在对手脚下做了点手脚',
        probability: 0.3,
        effects: [
          { type: 'modify_attribute', target: 'chr', value: -2, description: '魅力 -2（被发现了）' },
          { type: 'modify_attribute', target: 'str', value: 2, description: '体魄 +2（胜之不武）' },
          { type: 'set_flag', target: 'dirty_player', value: 1, description: '学会了不择手段' },
        ],
      },
    ],
    tag: 'life',
    priority: 'major',
  },
]
