import type { WorldPresetDef } from '../../engine/core/types'

export const presets: WorldPresetDef[] = [
  {
    id: 'random_1',
    name: '艾伦',
    title: '不知名的旅人',
    description: '来自边境村庄的年轻人，踏上了冒险之旅。',
    attributes: {},
    locked: false,
  },
  {
    id: 'random_2',
    name: '莉娜',
    title: '好奇心旺盛的少女',
    description: '城市出身的少女，对魔法和冒险充满向往。',
    attributes: {},
    locked: false,
  },
  {
    id: 'random_3',
    name: '加隆',
    title: '老兵之子',
    description: '退役骑士的儿子，继承了父亲的剑和意志。',
    attributes: {},
    talents: ['fighter_instinct'],
    locked: false,
  },
  {
    id: 'reincarnator',
    name: '???',
    title: '转生者',
    description: '睁开眼发现自己变成了一个婴儿。这一切…太熟悉了。',
    attributes: { int: 2, luk: 2 },
    talents: ['reincarnated'],
    locked: true,
    unlockCondition: '完成一局游戏',
  },
  {
    id: 'dragonborn',
    name: '阿尔维斯',
    title: '龙裔',
    description: '额头上有一枚龙鳞形状的胎记。',
    attributes: { str: 2, mag: 2 },
    talents: ['dragon_blood'],
    locked: true,
    unlockCondition: '解锁「屠龙者」成就',
  },
  {
    id: 'worldbreaker_preset',
    name: '漆黑之子',
    title: '终焉的预兆',
    description: '你出生的那天，天空中出现了一条裂缝。',
    attributes: { mag: 3, luk: 2, spr: 2 },
    talents: ['worldbreaker'],
    locked: true,
    unlockCondition: '解锁全部其他成就',
  },
]
